<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TRS [
<!ELEMENT TRS (REC)>
<!ELEMENT REC (SID,URLID,StartID,AttachID,PURLID,URLName,SiteName,Channel,URLTitle,GroupName,SRCName1,SRCName2,SRCName,LastTime,URLDate,URLTime,URLSize,URLTopic,ContentType,CharSet,Catalog1,Catalog2,Catalog,SimFlag,SimRank,TableFlag,ImageFlag,Content,URLTable,URLImage,PageLevel,PageRank,Authors,KeyWords,vAbstract,Urgency,SrcType,DocFormat,AttachSize,Attachment,URLBody,Receiver,CC,Infotype,Doccatalog,Modifyuser,Importance,Confid,Istop,Isrelease,Istrash,DelFlag,ReleaseTime,Label,status,CIS3C,CIS3D,CIS3P,CIS3N,CIS3B,CIS3T,ADDTIME,br)>
<!ELEMENT SID (#PCDATA | br)*>
<!ELEMENT URLID (#PCDATA | br)*>
<!ELEMENT StartID (#PCDATA | br)*>
<!ELEMENT AttachID (#PCDATA | br)*>
<!ELEMENT PURLID (#PCDATA | br)*>
<!ELEMENT URLName (#PCDATA | br)*>
<!ELEMENT SiteName (#PCDATA | br)*>
<!ELEMENT Channel (#PCDATA | br)*>
<!ELEMENT URLTitle (#PCDATA | br)*>
<!ELEMENT GroupName (#PCDATA | br)*>
<!ELEMENT SRCName1 (#PCDATA | br)*>
<!ELEMENT SRCName2 (#PCDATA | br)*>
<!ELEMENT SRCName (#PCDATA | br)*>
<!ELEMENT LastTime (#PCDATA | br)*>
<!ELEMENT URLDate (#PCDATA | br)*>
<!ELEMENT URLTime (#PCDATA | br)*>
<!ELEMENT URLSize (#PCDATA | br)*>
<!ELEMENT URLTopic (#PCDATA | br)*>
<!ELEMENT ContentType (#PCDATA | br)*>
<!ELEMENT CharSet (#PCDATA | br)*>
<!ELEMENT Catalog1 (#PCDATA | br)*>
<!ELEMENT Catalog2 (#PCDATA | br)*>
<!ELEMENT Catalog (#PCDATA | br)*>
<!ELEMENT SimFlag (#PCDATA | br)*>
<!ELEMENT SimRank (#PCDATA | br)*>
<!ELEMENT TableFlag (#PCDATA | br)*>
<!ELEMENT ImageFlag (#PCDATA | br)*>
<!ELEMENT Content (#PCDATA | br)*>
<!ELEMENT URLTable (#PCDATA | br)*>
<!ELEMENT URLImage (#PCDATA | br)*>
<!ELEMENT PageLevel (#PCDATA | br)*>
<!ELEMENT PageRank (#PCDATA | br)*>
<!ELEMENT Authors (#PCDATA | br)*>
<!ELEMENT KeyWords (#PCDATA | br)*>
<!ELEMENT vAbstract (#PCDATA | br)*>
<!ELEMENT Urgency (#PCDATA | br)*>
<!ELEMENT SrcType (#PCDATA | br)*>
<!ELEMENT DocFormat (#PCDATA | br)*>
<!ELEMENT AttachSize (#PCDATA | br)*>
<!ELEMENT Attachment (#PCDATA | br)*>
<!ELEMENT URLBody (#PCDATA | br)*>
<!ELEMENT Receiver (#PCDATA | br)*>
<!ELEMENT CC (#PCDATA | br)*>
<!ELEMENT Infotype (#PCDATA | br)*>
<!ELEMENT Doccatalog (#PCDATA | br)*>
<!ELEMENT Modifyuser (#PCDATA | br)*>
<!ELEMENT Importance (#PCDATA | br)*>
<!ELEMENT Confid (#PCDATA | br)*>
<!ELEMENT Istop (#PCDATA | br)*>
<!ELEMENT Isrelease (#PCDATA | br)*>
<!ELEMENT Istrash (#PCDATA | br)*>
<!ELEMENT DelFlag (#PCDATA | br)*>
<!ELEMENT ReleaseTime (#PCDATA | br)*>
<!ELEMENT Label (#PCDATA | br)*>
<!ELEMENT status (#PCDATA | br)*>
<!ELEMENT CIS3C (#PCDATA | br)*>
<!ELEMENT CIS3D (#PCDATA | br)*>
<!ELEMENT CIS3P (#PCDATA | br)*>
<!ELEMENT CIS3N (#PCDATA | br)*>
<!ELEMENT CIS3B (#PCDATA | br)*>
<!ELEMENT CIS3T (#PCDATA | br)*>
<!ELEMENT ADDTIME (#PCDATA | br)*>
<!ELEMENT br EMPTY>
]>
<TRS>
<REC>
<SID>40768056</SID><br/><br/>
<URLID>40768056</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>中评网</SiteName><br/><br/>
<URLTitle>日本海上自卫队舰船再次停靠越南金兰湾</URLTitle><br/><br/>
<SRCName>中评网</SRCName><br/><br/>
<LastTime>2016.05.30 14:09:35</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:08:15</URLTime><br/><br/>
<URLSize>241</URLSize><br/><br/>
<URLTopic>日本海上自卫队舰船再次停靠越南金兰湾</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;<br/>
&lt;P&gt;　　日本海上自卫队的扫雷母舰“浦贺”号与扫雷艇“高岛”号29日停靠越南中部军事重镇金兰湾的国际港。这是海上自卫队舰船第二次停靠该港。 <br/>
&lt;P&gt;<br/>
&lt;P&gt;　　共同社报道，出于对中国在南海活动日益活跃的警惕，日越两国正在加强防务合作。今年4月，海上自卫队2艘护卫舰首次停靠金兰湾。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　据日本驻越南大使馆介绍，“浦贺”号与“高岛”号结束在巴林的国际扫雷训练，在返程途中停靠金兰湾进行补给与休整。此次并没有与越南海军展开联合训练的计划。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wd</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:09:35</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>28119698</SID><br/><br/>
<URLID>28119698</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>环球网</SiteName><br/><br/>
<URLTitle>美驻华大使抨击本国媒体负面报道奥巴马访华</URLTitle><br/><br/>
<SRCName>环球网</SRCName><br/><br/>
<LastTime>2016.05.30 14:25:02</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:22:43</URLTime><br/><br/>
<URLSize>546</URLSize><br/><br/>
<URLTopic>美驻华大使抨击本国媒体负面报道奥巴马访华</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 据美联社报道，美国驻华大使洪博培11月20日对本国媒体进行了严厉批评，称美国媒体对总统奥巴马首次访华的报道过于负面，而忽略了访问所取得的重要成就。&lt;/P&gt;<br/>
&lt;P&gt;&lt;BR&gt;　　美联社称，奥巴马的首次访华成为了中国的头号新闻，中国公众对此次访问倾注了相当大的兴趣，他们对这位美国总统的看法也十分积极。然而，许多美国媒体的相关报道却严重负面，它们指责奥巴马未能在伊朗核问题、气候变化以及人权等关键问题上取得让步。&lt;/P&gt;<br/>
&lt;P&gt;&lt;BR&gt;　　洪博培表示，这些报道忽略了此次访问所产生的重要进步与合作，中美在清洁能源、军事交流以及阻止核扩散等方面都达成了重要共识。“我出席了奥巴马总统与胡锦涛主席和温家宝总理所举行的所有会议，”洪博培说，“我必须指出，我事后看到的一些报道是不正确的。”&lt;/P&gt;<br/>
&lt;P&gt;&lt;BR&gt;　　洪博培是在北京大学出席一个国际关系项目，同中美学生进行答问时作出上述表示的。&lt;/P&gt;<br/>
&lt;P&gt;&lt;BR&gt;　　洪博培还表示，华盛顿希望此次访问所带来的善意能够转化为具体的成就；未来在北京举行的战略对话将对此进行检验。他说：“（中美）已经拥有了一个积极的氛围，现在重要的是开始付诸实践。”&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wd</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:25:02</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>8786510</SID><br/><br/>
<URLID>8786510</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>俄罗斯卫星网</SiteName><br/><br/>
<URLTitle>叙最高谈判委员会首席谈判代表因日内瓦谈判失败有意辞职</URLTitle><br/><br/>
<SRCName>俄罗斯卫星网</SRCName><br/><br/>
<LastTime>2016.05.30 14:42:36</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:42:07</URLTime><br/><br/>
<URLSize>251</URLSize><br/><br/>
<URLTopic>叙最高谈判委员会首席谈判代表因日内瓦谈判失败有意辞职</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　叙利亚反对派最高谈判委员会首席谈判代表穆罕默德·阿卢什表示有意以辞职来抗议日内瓦叙利亚各方会谈的失败。 <br/>
&lt;P&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　上一轮叙利亚各方会谈4月在日内瓦结束。联合国叙利亚问题特使斯塔凡∙德米斯图拉未能让各方开始直接谈判。此外，受到利雅得支持的叙利亚反对派最高谈判委员会暂停参加会谈，该委员会指责叙利亚政府未履行国际决议并破坏停火。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　据德米斯图拉称，新一轮的会谈可能将被定于7月初举行。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wd</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>11</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:42:36</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281521997797203</SID><br/><br/>
<URLID>281521997797203</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://global.dwnews.com/news/2016-05-30/59742527.html</URLName><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>石油富国的末路：谁毁掉了委内瑞拉</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2016.05.30 14:39:56</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:23:15</URLTime><br/><br/>
<URLSize>1671</URLSize><br/><br/>
<URLTopic>石油富国的末路：谁毁掉了委内瑞拉</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　从未有哪个国家像委内瑞拉这样，在没有战争和天灾的情况下以层出不穷的社会新闻长期占据国际媒体头条。今天，委内瑞拉的新生儿死亡率达到了四年前的100倍，货币则比四年前贬值了99%，谋杀率高达全球第二，通货膨胀率则为全球第一——更可怕的是，目前已经超过了700%的通胀率并非谷底，2017年，委内瑞拉的通胀率很有可能将高达惊世骇俗的1642%。生活物资在过去的两年里逐渐陷入全面短缺，而该国在今年需要偿付的国际债务则高达160亿美元,超过了全部外汇总额。&lt;BR&gt;<br/>
&lt;P&gt;　　应对经济灾难，超发货币本是尽管饮鸩止渴，但短期内行之有效的应急办法，然而，今天的委内瑞拉政府甚至连这杯毒酒也已经买不起——由于付不出工资，印钞厂已经拒绝开工，而委内瑞拉玻利瓦尔纸币的价值在很多地区甚至不如一张普通纸巾。&lt;BR&gt;<br/>
&lt;P&gt;　　过去十几年里一度跃升为地区强国的委内瑞拉，为何沦落到了今天这一步？&lt;BR&gt;<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281521997797203_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;委内瑞拉国会已被反对党占领&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;油价无法解释一切&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　解读委内瑞拉经济离不开石油，但石油无法完全解释今天的委内瑞拉。&lt;BR&gt;<br/>
&lt;P&gt;　　过去的两年里，从俄罗斯到沙特，从巴西到伊拉克，被腰斩的国际油价给所有产油国经济都带来了明显阵痛，然而全世界产油国中只有委内瑞拉走向了崩溃边缘。根据委内瑞拉政府公布的官方数据，要想达到财政平衡，委内瑞拉需要的石油价格为121美元/桶——尽管短期内无法达到，但事实上这一数字也并不比同期俄罗斯或沙特所提出的需求数字高出多少，然而，只有委内瑞拉人在经历令全球为之骇然的经济灾难和社会失序。&lt;BR&gt;<br/>
&lt;P&gt;　　作为过去十几年里拉美左翼浪潮的领头羊，委内瑞拉正在经历历史上拉美左翼政府典型的“繁荣-瓶颈-衰退-崩溃”四阶段轮回：查韦斯执政的前十年里，石油红利惠及全体国民，该国绝对贫困人口从17%下降到8%，似乎强有力地证明了领导人的经济政策的正确性。但从2008年全球金融危机以后，委内瑞拉经济缺乏内生增长力的短板日益明显地暴露出来，不断上涨的通货膨胀与同步增加的收入水平共同对外汇储备造成压力，预算赤字问题因此而逐渐扩大。2014年开始的油价跳水将委内瑞拉彻底推进了轮回的第三阶段，国内出现普遍短缺和严重资本外逃，全面崩溃的阴影开始笼罩整个国家。&lt;BR&gt;<br/>
&lt;P&gt;　　但横向比较经济表现同样不佳的其他拉美邻国，委内瑞拉的真正特殊性在于，政治强人查韦斯在世的15年里，尽管经济隐患早早埋下，所有的矛盾却并未真正爆发，直到查韦斯因癌症辞世，被他“钦点”上台的新总统马杜罗面临内忧外患，一而再、再而三地被迫以并不突出的个人能力尝试挽大厦于将倾，才最终造成了今天几近无可挽回的灾难。&lt;BR&gt;<br/>
&lt;P&gt;　　总统一筹莫展&lt;BR&gt;<br/>
&lt;P&gt;　　早在查韦斯在世之时，其片面左倾的经济政策已经广受抨击，作为21世纪初拉美左翼运动的代表，查韦斯早早地选择了透支国家财政提高民众福利待遇，不但将石油价格上涨给经济带来的红利转手简单粗暴地发放给了民众，丝毫不考虑国家生产力、政府收入与民众福利水平的匹配问题，甚至还将事情做到了寅吃卯粮、靠超发货币来提高福利支出的程度。与这种自杀式的福利政策相应的还有查韦斯对于私有产权的践踏，毫无制度依托和法律保障可言的国有化严重伤害了私营业主的生产热情，而蔓延全国的裙带关系及腐败问题则进一步掏空了委内瑞拉本就基础薄弱的经济。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>查韦斯;委内瑞拉经济;末路;石油价格;灾难;委内瑞拉政府;货币;红利</KeyWords><br/><br/>
<vAbstract>委内瑞拉国会已被反对党占领（图源：VCG）油价无法解释一切解读委内瑞拉经济离不开石油，但石油无法完全解释今天的委内瑞拉。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:43:15</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>77706798</SID><br/><br/>
<URLID>77706798</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>希望之声</SiteName><br/><br/>
<URLTitle>反攻IS最后据点 伊拉克政府军展开行动</URLTitle><br/><br/>
<SRCName>希望之声</SRCName><br/><br/>
<LastTime>2016.05.30 14:43:45</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:42:36</URLTime><br/><br/>
<URLSize>701</URLSize><br/><br/>
<URLTopic>反攻IS最后据点 伊拉克政府军展开行动</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 伊拉克政府军目前正在对极端组织“伊斯兰国”（IS）最后的据点之一——费卢杰（Fallujah）发起攻击，而IS恐怖分子挟持平民進入交战区，加大了政府军的作战难度。&lt;BR&gt;<br/>
&lt;P&gt;　　据外媒报导，由美军协助的伊拉克政府军近日发起收复费卢杰的攻击，现已控制费卢杰附近的小镇卡尔马。同时，大量精锐部队已被派往费卢杰附近，随时准备对之发起攻击。&lt;BR&gt;<br/>
&lt;P&gt;　　但伊拉克政府军的收复行动遭到IS自杀炸弹的反击，而且IS恐怖分子还以5万平民作为肉盾，進行抵抗，政府军投鼠忌器，收复行动缓慢。&lt;BR&gt;<br/>
&lt;P&gt;　　联军旅长拉苏尔•叶海亚说：“我们正在推進中。平民的存在可能会延误我们。”&lt;BR&gt;<br/>
&lt;P&gt;　　另外，联合国消息也称，过去几天已经有800人从费卢杰逃脱，还有5万民众被IS抓获作为人质。&lt;BR&gt;<br/>
&lt;P&gt;　　费卢杰和另一城市摩苏尔是IS在伊拉克境内的最后两个据点。费卢杰地区有大约1700名IS人员，35万民众。&lt;BR&gt;<br/>
&lt;P&gt;　　过去的一周时间，联军在空袭伊拉克和叙利亚的部分地区取得進展，包括IS在费卢杰的指挥官马赫•比拉维（Maher al-Bilawi）等70多名圣战分子在空袭中丧生。&lt;BR&gt;<br/>
&lt;P&gt;　　另外，美军打击IS行动发言人沃伦13日表示，IS对于外国武装分子的吸引力越来越小。根据美军的评估，每月加入IS的外国武装分子数量现已骤降75%，实际战 斗人员的数量也在减少。来自联军的空袭、油价下跌及周边国家打击走私影响，使IS来自石油的年收入估计缩水一半到2.5亿美元左右。&lt;BR&gt;&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wd</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>11</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:43:45</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281521838615236</SID><br/><br/>
<URLID>281521838615236</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://www.chinesetoday.com/big/article/1110634</URLName><br/><br/>
<SiteName>国际日报</SiteName><br/><br/>
<Channel>中东</Channel><br/><br/>
<URLTitle>土耳其新政府贏得議會信任投票</URLTitle><br/><br/>
<GroupName>中东</GroupName><br/><br/>
<SRCName>国际日报</SRCName><br/><br/>
<LastTime>2016.05.30 06:33:46</LastTime><br/><br/>
<URLDate>2016.05.29</URLDate><br/><br/>
<URLTime>2016.05.29 09:59:50</URLTime><br/><br/>
<URLSize>406</URLSize><br/><br/>
<URLTopic>土耳其新政府贏得議會信任投票</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　由土耳其總理比納利·耶爾德勒姆領導的新一屆政府２９日贏得議會信任投票，新政府正式宣告成立。&lt;BR&gt;<br/>
&lt;P&gt;　　土耳其大國民議會共有議員５５０名，其中４５３名參加了當天的投票。結果顯示，３１５票贊成，１３８票反對。執政黨正義與發展黨（正發黨）在議會中佔有３１７席。&lt;BR&gt;<br/>
&lt;P&gt;　　耶爾德勒姆曾表示，新政府將堅決打擊恐怖主義勢力，推動憲法改革，改議會制為總統制。&lt;BR&gt;<br/>
&lt;P&gt;　　耶爾德勒姆在正發黨５月２２日舉行的特別代表大會上當選黨主席，土耳其總統埃爾多安授權耶爾德勒姆組建新一屆政府，並於２４日批准了新內閣成員名單。&lt;BR&gt;<br/>
&lt;P&gt;　　２０１４年８月，時任外長達武特奧盧當選正發黨第二任主席，並接替埃爾多安出任政府總理。本月５日，達武特奧盧宣佈辭去執政黨主席和總理職務。輿論普遍認為，達武特奧盧與埃爾多安在政體改革、應對外來難民及庫爾德工人黨等問題上存在分歧，最終導致了他的辭職。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>會信任投票;土耳其總;新政府;安卡拉;分歧;改革;主席;工人</KeyWords><br/><br/>
<vAbstract>耶爾德勒姆曾表示，新政府將堅決打擊恐怖主義勢力，推動憲法改革，改議會制為總統制。２０１４年８月，時任外長達武特奧盧當選正發黨第二任主席，並接替埃爾多安出任政府總理。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>11</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 07:55:22</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281521997907247</SID><br/><br/>
<URLID>281521997907247</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://sputniknews.cn/politics/20160530/1019479069.html</URLName><br/><br/>
<SiteName>俄罗斯卫星网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>日本政府评论有关人质消息称保护公民安全是其职责</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>俄罗斯卫星网</SRCName><br/><br/>
<LastTime>2016.05.30 14:40:01</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:40:01</URLTime><br/><br/>
<URLSize>507</URLSize><br/><br/>
<URLTopic>日本政府评论有关人质消息称保护公民安全是其职责</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　日本内阁官房长官菅义伟就疑似该国在叙利亚失踪的记者安田纯平的照片在媒体上流传一事表示，日本政府认为，保护本国公民安全是自己的基本职责。<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281521997907247_0.jpg&quot;&gt;&lt;/DIV&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　日政府正核实有关该国记者在叙被恐怖分子劫持消息菅义伟向记者表示：“保障日本公民的安全是政府最重要的职责。”&lt;BR&gt;<br/>
&lt;P&gt;　　此前有消息称，日本外务大臣岸田文雄和防卫大臣中谷元就此表示，正在对疑似安田纯平的新照片进行分析，并在搜集来自各个国家的必要情报信息。&lt;BR&gt;<br/>
&lt;P&gt;　　此前报道称，疑似去年在叙利亚失踪的安田纯平的照片昨天夜间被发给了媒体，并发出求助呼吁。&lt;BR&gt;<br/>
&lt;P&gt;　　据日媒报道称，一名自称是绑架了42岁日本记者的组织的中间人传播了这张照片。据推测，安田纯平正在叙利亚与“基地”组织恐怖网络有关的“胜利阵线”组织（在俄被禁止）手中。该媒体称，照片可能拍摄于5月28日。&lt;BR&gt;<br/>
&lt;P&gt;　&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>评论;消息;日本政府;公民;欧盟;职责;叙利亚;照片</KeyWords><br/><br/>
<vAbstract>您的评论将被版主审查是否符合规定添加更多所有评论显示新评论(0)评论回复在回复(显示评论隐藏评论)||编辑|删除保存谢谢！欧洲议会主席对10月土耳其获得欧盟免签待遇表示怀疑欧盟对土耳其获得欧盟免签待遇前景问题的立场保持不变。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:47:57</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281521997871678</SID><br/><br/>
<URLID>281521997871678</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://sputniknews.cn/politics/20160530/1019478075.html</URLName><br/><br/>
<SiteName>俄罗斯卫星网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>克里米亚政府呼吁联合国避免与封锁克里米亚半岛策划者会面</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>俄罗斯卫星网</SRCName><br/><br/>
<LastTime>2016.05.30 14:39:57</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:39:57</URLTime><br/><br/>
<URLSize>746</URLSize><br/><br/>
<URLTopic>克里米亚政府呼吁联合国避免与封锁克里米亚半岛策划者会面</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;<br/>
&lt;P&gt;　　克里米亚政府国际关系和被驱逐出境公民国家委员会负责人扎乌尔•斯米尔诺夫对俄新社表示，克里米亚政府呼吁联合国代表避免与封锁克里米亚半岛策划者进行会面，并在国际上宣布与其断交。 <br/>
&lt;P&gt;<br/>
&lt;P&gt;　　 <br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281521997871678_0.jpg&quot;&gt;&lt;/DIV&gt;&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　克里米亚，欧洲导弹防御系统与土耳其 - 普京在雅典重要声明的主题斯米尔诺夫称，联合国主管人权事务助理秘书长伊万•西蒙诺维奇与封锁克里米亚半岛策划者列法特•丘巴罗夫（Refat Chubarov）、穆斯塔法•杰米列夫(Mustafa Dzhemilev)和伊斯利亚莫夫•里努尔（Lenur Islyamova）最近在基辅的一次会面令克里米亚人感到愤慨。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　斯米尔诺夫表示：&apos;不能容忍像联合国这样权威国际组织同威胁克里米亚半岛200多万人生命的乌克兰极端分子会面。我们呼吁联合国代表避免同他们举行任何会见，并在国际上宣布与其断交。&apos;&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　他强调，任何与封锁克里米亚半岛组织者的会面都将被视为对克里米亚人民的不尊重以及对乌克兰极端分子的鼓励。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　克里米亚共和国总检察长娜塔莉亚•波克隆斯卡娅此前表示，已下令通缉对克里米亚半岛进行粮食和电力封锁的策划者，其中列法特•丘巴罗夫（Refat Chubarov）、穆斯塔法•杰米列夫(Mustafa Dzhemilev)遭国际通缉，伊斯利亚莫夫•里努尔（Lenur Islyamova）被联邦通缉。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>封锁;联合国;会面;评论;策划者;半岛;克里米亚政府;欧盟</KeyWords><br/><br/>
<vAbstract>您的评论将被版主审查是否符合规定添加更多所有评论显示新评论(0)评论回复在回复(显示评论隐藏评论)||编辑|删除保存谢谢！欧洲议会主席对10月土耳其获得欧盟免签待遇表示怀疑欧盟对土耳其获得欧盟免签待遇前景问题的立场保持不变。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>8</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:45:59</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281521953925765</SID><br/><br/>
<URLID>281521953925765</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://gb.cdnews.com.tw/cdnews_gb/docDetail.jsp?coluid=115&amp;docid=103695299</URLName><br/><br/>
<SiteName>环球网</SiteName><br/><br/>
<URLTitle>巴基斯坦：DNA检测证实塔利班头目曼苏尔被击毙</URLTitle><br/><br/>
<GroupName>测试</GroupName><br/><br/>
<SRCName>环球网</SRCName><br/><br/>
<LastTime>2016.05.30 12:31:23</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 12:30:53</URLTime><br/><br/>
<URLSize>388</URLSize><br/><br/>
<URLTopic>巴基斯坦：DNA检测证实塔利班头目曼苏尔被击毙</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 据《今日巴基斯坦报》5月30日报道，在美国无人机对巴基斯坦俾路支省展开空袭后一周，巴基斯坦内政部于周日表示，经过DNA检测，确认塔利班头目曼苏尔在袭击中身亡。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 巴基斯坦内政部发言人说道，曼苏尔的DNA与一名前来认领其尸体的亲属的DNA相符。巴基斯坦总理外交事务顾问则表示，所有迹象证明在无人机袭击中身亡的是曼苏尔。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 5月21日，美国无人机在阿富汗与巴基斯坦交界地带对曼苏尔进行定点清除，23日，美国总统奥巴马宣布确认塔利班头目曼苏尔在空袭中身亡。25日，塔利班方面对外证实了这一消息。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>约旦;医疗观光;签证;叶门;萎缩;利比亚;网路;病人</KeyWords><br/><br/>
<vAbstract>约旦虽为中东小国，但医疗水准比邻近国家先进，在中东素享盛名，最近几年在观光业带动下，医疗观光日益蓬勃。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>11</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:05:16</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>107607451</SID><br/><br/>
<URLID>107607451</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>环球网</SiteName><br/><br/>
<URLTitle>外媒：巴基斯坦考虑购歼-10取代购买F-16</URLTitle><br/><br/>
<SRCName>环球网</SRCName><br/><br/>
<LastTime>2016.05.30 14:48:43</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:48:14</URLTime><br/><br/>
<URLSize>1144</URLSize><br/><br/>
<URLTopic>外媒：巴基斯坦考虑购歼-10取代购买F-16</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;DIV class=Con_desp&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 巴基斯坦总理国际关系问题顾问萨尔塔基·阿济兹此前声明，如果华盛顿方面不向巴基斯坦方面提供补助金，伊斯兰堡方面已经准备向其他供应国购买歼击机。&lt;/DIV&gt;<br/>
&lt;DIV class=&quot;Con_detail line_h24 article-content&quot; style=&quot;MIN-HEIGHT: 270px&quot;&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 据Dawn报援引巴基斯坦外交消息人士的话报道，巴基斯坦在期限内并未接受美国在谈判框架下关于购买F-16的提议，F-16的购买协议濒临破产。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 美国在二月通过了向巴基斯坦出售8架G-16歼击机的合同。据悉，巴基斯坦将支付2.7亿美元，余下的金额将由美方自行负责。但美国国务院4月曾声明，无法在优惠条件下执行这一合同，而巴基斯坦方面则需要自行支付超过7亿美元购买这些飞机。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 巴基斯坦政府应在5月24日之前向美国提出接受这一提议的信函。但消息指出，巴基斯坦方面并未提出通过这一方案的信函，这证明美国方面的提案期限已经过期。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 受访者表示，“巴基斯坦方面决定，不能使用国家经费按照全额支付合同，因此合同(供应)条件已经失效。”&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 巴基斯坦驻美国大使贾利勒·阿巴斯·吉拉尼(Jalil Abbas Jilani)对该报表示，“但合同提案的最终期限还并没有到。”&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 巴基斯坦总理国际关系问题顾问萨尔塔基·阿济兹此前声明，如果华盛顿方面不向巴基斯坦方面提供补助金，伊斯兰堡方面已经准备向其他供应国购买歼击机。据某消息表示，伊斯兰堡对正在对向俄罗斯购买苏-35及向中国购买J10与J20进行研究。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 同时，Dunya新闻台表示，美国已通过Cessna公司向巴基斯坦出售6架飞机的合同，这6架飞机将由巴基斯坦的救援机构与医学机构使用。该合同价值14亿美元。&lt;/P&gt;&lt;/DIV&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wd</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>11</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:48:43</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>125334205</SID><br/><br/>
<URLID>125334205</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>环球网</SiteName><br/><br/>
<URLTitle>沙特：伊朗军事介入伊拉克“无法接受”应停止插手</URLTitle><br/><br/>
<SRCName>环球网</SRCName><br/><br/>
<LastTime>2016.05.30 14:44:33</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 14:43:45</URLTime><br/><br/>
<URLSize>640</URLSize><br/><br/>
<URLTopic>沙特：伊朗军事介入伊拉克“无法接受”应停止插手</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 据美联社5月29日报道，在伊朗支持的数千名伊拉克什叶派民兵、士兵和警察包围了逊尼派城市费卢杰(Fallujah)后，沙特阿拉伯外交部长朱拜尔29日表示，对伊朗军事介入伊拉克的事实“无法接受”，并要求伊朗必须停止插手。&lt;/P&gt;<br/>
&lt;P&gt;　　在29日沙特与英国外交大臣哈蒙德举行的联合记者招待会上，朱拜尔表示，伊朗这是通过政策手段“在伊拉克播撒叛乱和分裂的种子”。伊朗则表示，派军事顾问到伊拉克是应伊拉克的要求以帮助其军队对抗武装分子。&lt;/P&gt;<br/>
&lt;P&gt;　　报道补充称，今年1月，伊朗示威者冲击了沙特驻伊朗大使馆，以抗议沙特将一位知名什叶派神职人员处决，两国外交关系也因此断绝。而这一紧张局势也已影响到一年一度的麦加朝觐。&lt;/P&gt;<br/>
&lt;DIV id=adPp class=&quot;ad250x250 fLeft marRig10&quot;&gt;&lt;/DIV&gt;<br/>
&lt;P&gt;　　为使伊朗朝圣者能够参加9月的麦加朝觐，伊朗代表团与沙特又进行了一轮谈判，但没有达成一致协议，随后伊朗代表团便离开了沙特。沙特表示，它不可能接受伊朗提出的要求，允许反抗西方和经常冲击沙特的抗议者在麦加朝觐期间举行什叶派的仪式。伊朗朝圣组织称，沙特没有满足朝圣者提出的“安全和尊重” 的要求。同时，伊朗文化部长阿里•贾纳提(Ali&amp;nbsp;Jannati)29日表示，沙特所谓的“破坏和阻碍”的意思是“伊朗朝圣者今年不能去麦加朝觐”。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wd</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>11</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 14:44:33</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281522027228455</SID><br/><br/>
<URLID>281522027228455</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://www.voachinese.com/content/iraq-20160530/3351561.html</URLName><br/><br/>
<SiteName>VOA</SiteName><br/><br/>
<Channel>中东</Channel><br/><br/>
<URLTitle>伊拉克军队攻打费卢杰 被困平民处境恶化</URLTitle><br/><br/>
<GroupName>中东</GroupName><br/><br/>
<SRCName>VOA</SRCName><br/><br/>
<LastTime>2016.05.30 15:34:48</LastTime><br/><br/>
<URLDate>2016.05.30</URLDate><br/><br/>
<URLTime>2016.05.30 15:34:48</URLTime><br/><br/>
<URLSize>569</URLSize><br/><br/>
<URLTopic>伊拉克军队攻打费卢杰 被困平民处境恶化</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　伊拉克军方领导人说，安全部队星期一从几个方向进攻被伊斯兰国极端分子占据的城市费卢杰，发动了收复这座城市的行动。&lt;BR&gt;<br/>
&lt;P&gt;　　伊拉克反恐精锐部队的发言人诺尔曼对法新社说：“我们星期一清晨对费卢杰发动了攻势。”&lt;BR&gt;<br/>
&lt;P&gt;　　在战斗打响之际，人们更加关注被困在这座城市里的平民所处的困境。&lt;BR&gt;<br/>
&lt;P&gt;　　伊拉克特种部队军人穆罕默德正在前线作战，他在电话采访中说，“伊斯兰国在街道上安放炸弹，他们还有自杀爆炸手。我们正在等待号令，杀进城去消灭伊斯兰国。”&lt;BR&gt;<br/>
&lt;P&gt;　　逊尼派重镇费卢杰是被伊斯兰国占据时间最长的伊拉克城市，据信伊斯兰国的势力在费卢杰盘根错节。&lt;BR&gt;<br/>
&lt;P&gt;　　随着费卢杰周围的战斗和空袭日益激烈，被困平民的处境更为恶化。虽然有大约800人逃出城外，但还有数千人被困。&lt;BR&gt;<br/>
&lt;P&gt;　　联合国难民署说，他们收到有关平民遭受苦难的可怕报告。&lt;BR&gt;<br/>
&lt;P&gt;　　联合国难民署发言人弗莱明说： “我们收到令人震惊的报告，越来越多的男人和年龄大些的男孩因为不肯为伊斯兰国作战而被处决。还有报告说，试图逃离的人被处决或遭鞭刑。另外，在持续不断的军事行动中，据报有很多人在自己家中被杀，或被自己住房的瓦砾所埋葬。”&lt;BR&gt;<br/>
&lt;P&gt;　　联合国的人道主义机构不断呼吁允许平民离开这座城市。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>费卢杰;伊拉克;平民;伊斯兰;处境;城市;恶化;攻打</KeyWords><br/><br/>
<vAbstract>伊拉克军方领导人说，安全部队星期一从几个方向进攻被伊斯兰国极端分子占据的城市费卢杰，发动了收复这座城市的行动。联合国的人道主义机构不断呼吁允许平民离开这座城市。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wd</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2016.05.30 15:35:17</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>121182302</SID><br/><br/>
<URLID>121182302</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<URLTitle>普京在希腊就四大问题强力发声</URLTitle><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2016.05.29 13:41:14</LastTime><br/><br/>
<URLDate>2016.05.29</URLDate><br/><br/>
<URLTime>2016.05.29 13:40:57</URLTime><br/><br/>
<URLSize>1637</URLSize><br/><br/>
<URLTopic>普京在希腊就四大问题强力发声</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　俄罗斯总统普京5月27日抵达希腊首都雅典，开始为期两天的访问。这是普京今年首次访问欧盟国家。普京在与希腊总理齐普拉斯的联合会谈上就当前俄罗斯面临的四大问题发表了声明。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　关于美国在罗马尼亚部署部署导弹防御系统&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　普京表示，罗马尼亚部署反导系统时可能会安装打击系统，只需要改变软件设备就可以，俄罗斯将被迫做出还击行为。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　普京说，“这是发射系统和雷达站。现在那里部署的是射程为500公里的导弹。过几年将部署射程为1000公里的导弹”。他认为，这威胁着俄罗斯的核力量。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　他认为，俄罗斯被迫以这种方式做出回应。普京说，“我们被迫做出某种行动，从而保障我们的安全。重复一遍——这是还击行为”。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　普京说，波兰部署反导系统时也会发生同样的事。他表示，俄罗斯有海基和空基导弹中程导弹，还有射程为500公里的“伊斯坎德尔”陆地导弹系统。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　关于克里米亚&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　普京在评论乌克兰总统波罗申科（Petro Poroshenko）关于乌克兰政府将在乌克兰军人娜杰日塔·萨夫琴科之后被归还克里米亚半岛的话时表示，克里米亚问题已经关闭。&lt;BR&gt;<br/>
&lt;P&gt;<br/>