<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TRS [
<!ELEMENT TRS (REC)>
<!ELEMENT REC (SID,URLID,StartID,AttachID,PURLID,URLName,SiteName,Channel,URLTitle,GroupName,SRCName1,SRCName2,SRCName,LastTime,URLDate,URLTime,URLSize,URLTopic,ContentType,CharSet,Catalog1,Catalog2,Catalog,SimFlag,SimRank,TableFlag,ImageFlag,Content,URLTable,URLImage,PageLevel,PageRank,Authors,KeyWords,vAbstract,Urgency,SrcType,DocFormat,AttachSize,Attachment,URLBody,Receiver,CC,Infotype,Doccatalog,Modifyuser,Importance,Confid,Istop,Isrelease,Istrash,DelFlag,ReleaseTime,Label,status,CIS3C,CIS3D,CIS3P,CIS3N,CIS3B,CIS3T,ADDTIME,br)>
<!ELEMENT SID (#PCDATA | br)*>
<!ELEMENT URLID (#PCDATA | br)*>
<!ELEMENT StartID (#PCDATA | br)*>
<!ELEMENT AttachID (#PCDATA | br)*>
<!ELEMENT PURLID (#PCDATA | br)*>
<!ELEMENT URLName (#PCDATA | br)*>
<!ELEMENT SiteName (#PCDATA | br)*>
<!ELEMENT Channel (#PCDATA | br)*>
<!ELEMENT URLTitle (#PCDATA | br)*>
<!ELEMENT GroupName (#PCDATA | br)*>
<!ELEMENT SRCName1 (#PCDATA | br)*>
<!ELEMENT SRCName2 (#PCDATA | br)*>
<!ELEMENT SRCName (#PCDATA | br)*>
<!ELEMENT LastTime (#PCDATA | br)*>
<!ELEMENT URLDate (#PCDATA | br)*>
<!ELEMENT URLTime (#PCDATA | br)*>
<!ELEMENT URLSize (#PCDATA | br)*>
<!ELEMENT URLTopic (#PCDATA | br)*>
<!ELEMENT ContentType (#PCDATA | br)*>
<!ELEMENT CharSet (#PCDATA | br)*>
<!ELEMENT Catalog1 (#PCDATA | br)*>
<!ELEMENT Catalog2 (#PCDATA | br)*>
<!ELEMENT Catalog (#PCDATA | br)*>
<!ELEMENT SimFlag (#PCDATA | br)*>
<!ELEMENT SimRank (#PCDATA | br)*>
<!ELEMENT TableFlag (#PCDATA | br)*>
<!ELEMENT ImageFlag (#PCDATA | br)*>
<!ELEMENT Content (#PCDATA | br)*>
<!ELEMENT URLTable (#PCDATA | br)*>
<!ELEMENT URLImage (#PCDATA | br)*>
<!ELEMENT PageLevel (#PCDATA | br)*>
<!ELEMENT PageRank (#PCDATA | br)*>
<!ELEMENT Authors (#PCDATA | br)*>
<!ELEMENT KeyWords (#PCDATA | br)*>
<!ELEMENT vAbstract (#PCDATA | br)*>
<!ELEMENT Urgency (#PCDATA | br)*>
<!ELEMENT SrcType (#PCDATA | br)*>
<!ELEMENT DocFormat (#PCDATA | br)*>
<!ELEMENT AttachSize (#PCDATA | br)*>
<!ELEMENT Attachment (#PCDATA | br)*>
<!ELEMENT URLBody (#PCDATA | br)*>
<!ELEMENT Receiver (#PCDATA | br)*>
<!ELEMENT CC (#PCDATA | br)*>
<!ELEMENT Infotype (#PCDATA | br)*>
<!ELEMENT Doccatalog (#PCDATA | br)*>
<!ELEMENT Modifyuser (#PCDATA | br)*>
<!ELEMENT Importance (#PCDATA | br)*>
<!ELEMENT Confid (#PCDATA | br)*>
<!ELEMENT Istop (#PCDATA | br)*>
<!ELEMENT Isrelease (#PCDATA | br)*>
<!ELEMENT Istrash (#PCDATA | br)*>
<!ELEMENT DelFlag (#PCDATA | br)*>
<!ELEMENT ReleaseTime (#PCDATA | br)*>
<!ELEMENT Label (#PCDATA | br)*>
<!ELEMENT status (#PCDATA | br)*>
<!ELEMENT CIS3C (#PCDATA | br)*>
<!ELEMENT CIS3D (#PCDATA | br)*>
<!ELEMENT CIS3P (#PCDATA | br)*>
<!ELEMENT CIS3N (#PCDATA | br)*>
<!ELEMENT CIS3B (#PCDATA | br)*>
<!ELEMENT CIS3T (#PCDATA | br)*>
<!ELEMENT ADDTIME (#PCDATA | br)*>
<!ELEMENT br EMPTY>
]>
<TRS>
<REC>
<SID>281516425630815</SID><br/><br/>
<URLID>281516425630815</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://cn.reuters.com/article/2015/12/02/myanmar-politics-idCNKBS0TL0BA20151202</URLName><br/><br/>
<SiteName>路透社</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>昂山素季与缅甸总统吴登盛会晤</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>路透社</SRCName><br/><br/>
<LastTime>2015.12.02 14:33:20</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 14:32:01</URLTime><br/><br/>
<URLSize>385</URLSize><br/><br/>
<URLTopic>昂山素季与缅甸总统吴登盛会晤</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　缅甸全国民主联盟（民盟）领导人昂山素季周三与总统吴登盛会晤。民盟本月早些时候在议会选举中取得压倒性胜利。<br/>
&lt;P&gt;　　民盟在选举中获胜后不久，昂山素季就提出愿与吴登盛以及国防军总司令敏昂莱（Min Aung Hlaing）磋商寻求和解。&lt;BR&gt;<br/>
&lt;P&gt;　　总统府官员称，昂山素季周三上午抵达总统官邸。她下午还将与敏昂莱会晤。&lt;BR&gt;<br/>
&lt;P&gt;　　昂山素季愿与军方合作，但明确表示希望修改部分宪法，包括规定配偶或子女为外国人的缅甸人不得竞选总统的条款。&lt;BR&gt;<br/>
&lt;P&gt;　　目前还不清楚民盟执政后是打算谨慎行事，还是会冒险寻求削弱军方的政治影响力。基于缅甸宪法，上下议院均为军方保留四分之一的席位，这意味着军方足以对修宪行使否决权。&lt;BR&gt;<br/>
&lt;P&gt;　　吴登盛和敏昂莱均已表态认同选举结果，并表示愿推动明年2-4月新政府平稳过渡。&lt;BR&gt;<br/>
&lt;P&gt;　　&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>民盟;昂山素季;军方;选举;吴登盛;缅甸;志愿者;经济增长</KeyWords><br/><br/>
<vAbstract>“资产荒”引发信用债配置热情更多路透资讯伦敦警察高官称伦敦警方可应对巴黎式恐怖袭击奥巴马敦促土耳其缓解与俄罗斯的紧张关系习近平访问津巴布韦出席10项双边经济协议签约仪式美高官称美国扩大对“伊斯兰国”石油供应链的轰炸范围北约盟国拟采取行动以加强土耳其的防空力量多媒体新闻图片新闻。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>zym</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.02 14:35:35</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281516426766545</SID><br/><br/>
<URLID>281516426766545</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://sputniknews.cn/russia/20151202/1017219639.html</URLName><br/><br/>
<SiteName>俄新网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>日外相未否认安倍访俄可能</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>俄新网</SRCName><br/><br/>
<LastTime>2015.12.02 14:33:53</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 14:32:36</URLTime><br/><br/>
<URLSize>340</URLSize><br/><br/>
<URLTopic>日外相未否认安倍访俄可能</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　他在回答报纸记者有关安倍访俄可能的问题时表示：&apos;两国领导人的对话非常重要，以何种方式进行对话则是将来的问题。&apos; 日本首相安倍晋三2013年春天访问过莫斯科。俄总统普京原定于2014年秋天进行回访，但因乌克兰危机导致国际局势日趋复杂未能成行。访问时间被推迟至2015年，但具体日期一直没有透露。&lt;BR&gt;<br/>
&lt;P&gt;　　在回答报纸关于若安倍在普京访日前再度访俄是否会破坏访问次序的问题时，岸田文雄指出，&apos;现在没有任何关于何人按何种次序做什么的决定。&apos;&lt;BR&gt;<br/>
&lt;P&gt;　　普京与安倍晋三在土耳其安塔利亚G20峰会期间进行了会晤。俄总统新闻秘书德米特里·佩斯科夫表示，会谈中双方谈及了和平条约和普京访日问题。佩斯科夫补充称：&apos;在此之前，日本首相可能会访问俄罗斯某地区。&apos;&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>普京访;安倍访;安倍晋;访问;佩斯科夫;外相;领导人;次序</KeyWords><br/><br/>
<vAbstract>他在回答报纸记者有关安倍访俄可能的问题时表示：&quot;两国领导人的对话非常重要，以何种方式进行对话则是将来的问题。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>zym</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.02 14:35:46</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281502666724824</SID><br/><br/>
<URLID>281502666724824</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://www.worldjournal.com/3557515/article-%e7%bf%92%e6%9c%83%e6%ad%90%e5%a0%85%e6%8c%81%e4%b8%8d%e8%a1%9d%e7%aa%81%e3%80%81%e5%8f%b0%e6%b5%b7%e5%92%8c%e5%b9%b3/?variant=zh-cn&amp;ref=%B9%FA%BC%CA</URLName><br/><br/>
<SiteName>世界新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>习会欧:坚持不冲突、台海和平</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>世界新闻网</SRCName><br/><br/>
<LastTime>2015.12.01 06:42:29</LastTime><br/><br/>
<URLDate>2015.12.01</URLDate><br/><br/>
<URLTime>2015.12.01 06:41:06</URLTime><br/><br/>
<URLSize>736</URLSize><br/><br/>
<URLTopic>习会欧:坚持不冲突、台海和平</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;<br/>
&lt;P&gt;　　中国国家主席习近平30日在巴黎会见美国总统欧巴马，就中美关系发展及共同关心的国际和地区问题深入交换意见。双方同意继续推进中美关系向前发展以及加强应对气候变化领域合作。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　关于台湾问题，习近平指出，维护台海和平稳定，符合中美共同利益。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　新华社报导，习近平指出，今年9月，中国对美国进行了成功的国事访问，推动中美关系取得新进展，双方在经贸、两军、人文等领域以及重大国际地区问题上保持了有效协调和合作。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　习近平强调，当前形势下，中美两国要牢牢把握构建新型大国关系正确方向，坚持不冲突不对抗、相互尊重、合作共赢原则，从双边、地区、全球各个层面推进两国务实交流合作关于台湾问题，习近平指出，维护台海和平稳定，符合中美共同利益。希望美方以实际行动支持两岸关系和平发展。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　欧巴马表示，习主席今年9月对美国的国事访问非常成功，美中在不久前结束的二十国集团峰会和亚太经合组织领导人非正式会议期间进行了很好的沟通。当前形势下，美中两国共同利益不断增多，双方在更广泛领域保持协调合作十分必要。欧巴马早前对巴黎联合国气候峰会表示，美国身为全球第二大温室气体排放国，会承担协助改善气候变迁的责任，并指全球减排行动不需要伤害到经济成长。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　在超过150个全球领导人参加的巴黎联合国气候峰会上，欧巴马指出，气候变迁威胁越来越大，对本世纪轮廓的形塑，可能比任何时候都要剧烈。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　欧巴马说：“身为全球最大经济体与第二大排放国的领导人...美国不仅意识到我们在制造此问题上的角色，也扛起想办法解决的责任。”&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>习近平;巴马;领导人;冲突;台海和平稳定;气候;排放国;坚持</KeyWords><br/><br/>
<vAbstract>习近平强调，当前形势下，中美两国要牢牢把握构建新型大国关系正确方向，坚持不冲突不对抗、相互尊重、合作共赢原则，从双边、地区、全球各个层面推进两国务实交流合作关于台湾问题，习近平指出，维护台海和平稳定，符合中美共同利益。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.01 09:29:26</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281516875942337</SID><br/><br/>
<URLID>281516875942337</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://global.dwnews.com/news/2015-12-02/59700093.html</URLName><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>嫉妒成疾？人民币入篮日本让中国别太骄傲</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2015.12.02 15:31:56</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 14:22:32</URLTime><br/><br/>
<URLSize>1843</URLSize><br/><br/>
<URLTopic>嫉妒成疾？人民币入篮日本让中国别太骄傲</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　人民币纳入特别提款权（SDR）货币篮子，得到国际货币基金组织（IMF）的认可引发各国媒体热议。尤其反应过度的是日本，有很多日本媒体已经表露出人民币入篮而撼动日元地位的担忧，然而却硬要说，中国不要骄傲。&lt;BR&gt;<br/>
&lt;P&gt;　　日本《经济新闻》中文网12月2日报道，作为特别提款权（SDR）这一国际储备货币的构成货币，国际货币基金组织（IMF）决定从2016年10月起纳入人民币。中国迎来了加紧推进货币和金融制度改革，使人民币成为与这一地位相符货币的时刻。&lt;BR&gt;<br/>
&lt;P&gt;　　SDR是IMF分配给会员国的一种“储备货币”。目前由美元、欧元、英镑和日元4种货币构成，人民币加入之后构成货币将增至5种。SDR的价值通过结合构成货币而决定的“货币篮子方式”确定。新的构成货币权重方面，人民币将仅次于美元和欧元、位居第3位，超过日元和英镑。&lt;BR&gt;<br/>
&lt;P&gt;　　由于人民币获得了作为国际货币的“公认”，各国政府和央行易于将人民币纳入外汇储备。另一方面，由于并非在金融市场上实际对SDR进行买卖，所以短期内的影响有限。&lt;BR&gt;<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281516875942337_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;人民币找到了自己原有的地位&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　从目前来看，全球第2大经济体中国的货币成为国际货币，这一象征性意义更大。人民币被纳入SDR，加上中国主导的亚洲基础设施投资银行（AIIB）的成立，显示出此前一直由日美欧主导的战后国际货币体制迎来了转折点。&lt;BR&gt;<br/>
&lt;P&gt;　　中国人民银行（央行）8月份在下调人民币兑美元汇率中间价的同时，改为采用汇率市场化机制使人民币汇率符合市场实际情况。虽然与市场的对话仍存在课题，不过中国央行此举获得了要求实施市场化改革的IMF的理解，在促进人民币纳入SDR的计划中发挥了作用。&lt;BR&gt;<br/>
&lt;P&gt;　　但是，人民币交易目前仍然受限。虽然中国国内正在推进利率自由化，但跨境的货币、股票及债券等资本交易仍存在限制。中国不应该因人民币别纳入SDR而居高自傲，而是必须立即进一步推进旨在实现自由化的金融市场和外汇制度的改革。&lt;BR&gt;<br/>
&lt;P&gt;　　报道称， 如果个人和企业无法自由进行人民币和外币兑换，那就无法成为真正的国际货币。为了确保出口竞争力，中国当局是否真的不会诱导人民币贬值？目前仍然存在不确定性。&lt;BR&gt;<br/>
&lt;P&gt;　　中国正筹备在英国伦敦发行以人民币计价的国债。人民币在离岸市场的交易也被认为将出现扩大的趋势。在人民币交易的便利性方面，日本落后于欧洲。希望中日两国当局能进一步推进金融合作，以提高两国企业和个人之间的金融便利性。&lt;BR&gt;<br/>
&lt;P&gt;　　另据共同社1日报道称，际货币基金组织（IMF）决定将人民币纳入特别提款权（SDR）货币篮子，认可了人民币作为主要货币。似乎欲挑战以美元为中心的二战后的国际货币体系，中国将通过实现现代丝绸之路经济圈构想等，大举扩大人民币的势力范围。&lt;BR&gt;<br/>
&lt;P&gt;　　报道称，不少市场人士认为“根据中国作为世界第二大经济体的实际情况，人民币一直仅作为区域性货币是很困难的”（日本某大型银行系统智库人士语）。野村证券公司首席经济师木下智夫分析称：“如果能实现外汇兑换及资本交易的自由化，人民币在遥远的将来有可能成为威胁美元的存在。”&lt;BR&gt;<br/>
&lt;P&gt;　　《朝日新闻》的报道称，人民币入篮的决定将于2016年10月1日生效，这进一步突显了中国经济在全球市场中的重要地位。《东京新闻》报道称，IMF给了人民币国际主要货币的地位。今后，将会有越来越多的国际为了规避风险，除美元、日元、欧元和英镑外，还会储备人民币。中国的国际地位也会进一步提升。&lt;BR&gt;<br/>
&lt;P&gt;　　更多的日本媒体聚焦于人民币入SDR给日元造成的冲击。《读卖新闻》的文章表示，人民币纳入SDR，并占有10.92%的权重。这个比重超过了日元的8.33%，成为全球贸易结算中占据第三位的货币。日元的地位岌岌可危，已经让不少日本人深感担忧。可以看出，日本别让中国因人民币入SDR而过于骄傲实属妒而不得的表现。他们更担心日元的地位被彻底撼动。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>货币;国际;纳入 SDR;日本;中国;地位;人民币入;欧元</KeyWords><br/><br/>
<vAbstract>人民币找到了自己原有的地位从目前来看，全球第2大经济体中国的货币成为国际货币，这一象征性意义更大。另据共同社1日报道称，际货币基金组织（IMF）决定将人民币纳入特别提款权（SDR）货币篮子，认可了人民币作为主要货币。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.02 15:30:54</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281516875426205</SID><br/><br/>
<URLID>281516875426205</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://sputniknews.cn/politics/20151202/1017220559.html</URLName><br/><br/>
<SiteName>俄新网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>土耳其需关闭与叙利亚的边界 否则与“伊斯兰国”(又称达伊沙)的斗争可拖延</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>俄新网</SRCName><br/><br/>
<LastTime>2015.12.02 15:31:58</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 15:30:41</URLTime><br/><br/>
<URLSize>350</URLSize><br/><br/>
<URLTopic>土耳其需关闭与叙利亚的边界 否则与“伊斯兰国”(又称达伊沙)的斗争可拖延</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　美国总统奥巴马1日表示，安卡拉应加大对土耳其与叙利亚边界的防卫，避免恐怖分子通过；因有约98公里长的土叙边界被用于为&apos;伊斯兰国&apos;恐怖分子补充物资和人员。&lt;BR&gt;<br/>
&lt;P&gt;　　晚些时候美参谋长联席会议主席约瑟夫·邓福德上将表示，制止武装分子进入叙利亚至关重要，且需要在100多个国家之间更加有效地交换信息。&lt;BR&gt;<br/>
&lt;P&gt;　　科布说：&apos;邓福德上将的提议是合理的。如果我们不能制止其它国家的武装分子流入，与‘伊斯兰国&apos;的斗争的持续时间会久得多。如果土耳其关闭与叙利亚的边界，这些人会更难以到达他们设法前往的地方。&apos;&lt;BR&gt;<br/>
&lt;P&gt;　　美国国防部长阿什顿·卡特1日表示，土耳其必须在打击&apos;伊斯兰国&apos;上做出更多，他指出，土耳其的大部分行动都是针对库尔德工人党，而不是针对&apos;伊斯兰国&apos;的。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>伊斯兰国;土耳其;边界;叙利亚;关闭;达伊;恐怖分子;斗争</KeyWords><br/><br/>
<vAbstract>因有约98公里长的土叙边界被用于为&quot;伊斯兰国&quot;恐怖分子补充物资和人员。如果土耳其关闭与叙利亚的边界，这些人会更难以到达他们设法前往的地方。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.02 15:32:15</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281516875454040</SID><br/><br/>
<URLID>281516875454040</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://sputniknews.cn/politics/20151202/1017220646.html</URLName><br/><br/>
<SiteName>俄新网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>美总统候选人希拉里·克林顿称愿与俄合作打击“伊斯兰国”</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>俄新网</SRCName><br/><br/>
<LastTime>2015.12.02 15:31:59</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 15:30:42</URLTime><br/><br/>
<URLSize>458</URLSize><br/><br/>
<URLTopic>美总统候选人希拉里·克林顿称愿与俄合作打击“伊斯兰国”</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　她表示：&apos;我们应拒绝在打击阿萨德还是打击‘伊斯兰国&apos;之间做选择。我想，我们可以两者都打击。&apos;她提醒说：&apos;沙姆沙伊赫飞机爆炸事件使俄罗斯人付出了高昂代价，因此他们因‘伊斯兰国&apos;而损失了本国公民。&apos;&lt;BR&gt;<br/>
&lt;P&gt;　　她指出：&apos;我会对他们说，即使没有你们的积极支持，我们也需要哪怕是在打击‘伊斯兰国&apos;行动上的让步。&apos;但她同时强调，自己目前无法想象将美军派往伊拉克或叙利亚的情况。&lt;BR&gt;<br/>
&lt;P&gt;　　克林顿表示，如果俄罗斯愿意参加此进程，美国也会很高兴。她补充称：&apos;我们知道，你们也有自己的利益，你们为高加索的局势，以及‘伊斯兰国&apos;意识形态可能蔓延感到担忧。&apos;&lt;BR&gt;<br/>
&lt;P&gt;　　她在回答主持人关于自己若胜选，可能在叙利亚设立禁飞区的问题时称，那样的话就不会发生俄飞机被击落事件了。她解释称：&apos;我们将设立禁飞区，俄罗斯将被明确告知。&apos;&lt;BR&gt;<br/>
&lt;P&gt;　　此前美国政客表示有必要在叙利亚设立禁飞区，以保护叙利亚&apos;温和&apos;反对派免遭空袭。媒体还援引克林顿的言论称，在叙设立禁飞区，不能没有俄罗斯的参与。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>克林顿;叙利亚;打击;设立;俄罗斯;伊斯兰国;候选人;飞机</KeyWords><br/><br/>
<vAbstract>&quot;她在回答主持人关于自己若胜选，可能在叙利亚设立禁飞区的问题时称，那样的话就不会发生俄飞机被击落事件了。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.02 15:33:19</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281516876072991</SID><br/><br/>
<URLID>281516876072991</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://global.dwnews.com/news/2015-12-02/59700095.html</URLName><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>伊斯兰世界内讧不断  ISIS临灭顶之灾？</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2015.12.02 15:32:02</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 15:30:27</URLTime><br/><br/>
<URLSize>2074</URLSize><br/><br/>
<URLTopic>伊斯兰世界内讧不断  ISIS临灭顶之灾？</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　近日全球最大的穆斯林国家印度尼西亚宣布印尼穆斯林对ISIS教义宣战，作为世界上穆斯林最多的国家，信众超过2亿人。本次高调发声也说明了伊斯兰世界对ISIS（伊斯兰国）意识形态的否定。&lt;BR&gt;<br/>
&lt;P&gt;　　据媒体报道，世界最大的穆斯林国家印度尼西亚高调宣布将对伊斯兰国的意识形态宣战，印度尼西亚前总统阿卜杜拉赫曼•瓦希德(Abdurrahman Wahid)说：“许多背诵《古兰经》和《圣训》的人都喜欢斥责其他人为异教徒，却忽略了自己对真主的背弃，他们的心灵和思想仍深陷于污秽之中。”从宗教角度对伊斯兰国（又称ISIS）的无情否定，也标志伊斯兰世界对ISIS的意识形态战争。&lt;BR&gt;<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281516876072991_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;狂热的伊斯兰国武装分子&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　当下，大国在叙利亚问题上的博弈已非秘密，美俄德法相继加入这场以ISIS为棋子的博弈，而从意识形态领域来看一场伊斯兰世界对ISIS的战争也正在悄悄打响。世界对伊斯兰国存在多种版本的误解，ISIS遵循的是一种独特的伊斯兰教派，它对通往最终审判之路（末日圣战）的信念影响着它的战略。&lt;BR&gt;<br/>
&lt;P&gt;　　走向极端的ISIS教义&lt;BR&gt;<br/>
&lt;P&gt;　　ISIS制定的所有主要决策和法律，都遵循它自己声称的，被广泛公布在其宣传板、车牌、文具和硬币上的“先知方式”，即事无巨细，都遵循先知穆罕默德的教诲，或者其实际行为。由此来看，ISIS才是地地道道的伊斯兰。它的大部分信众都来自中东和欧洲未受波及的地区。但它最忠实的追随者所宣扬的教义，源自对伊斯兰最直接甚至是最深刻的解读。&lt;BR&gt;<br/>
&lt;P&gt;　　它的社会福利制度完全按照伊斯兰教法制定，卫生保健是免费的。提供平等的就业机会和食物及社会福利，ISIS认为这才是真主法律的要求。在媒体看来，它的崛起与埃及穆斯林兄弟会的成功不同，而更像大卫•考雷什或吉姆•琼斯之类的反乌托邦主义再世，不过它以绝对权力统治着伊拉克和叙利亚近八百万人口。&lt;BR&gt;<br/>
&lt;P&gt;　　这个“国家”原则上拒绝和平，渴望种族屠杀，严格遵循伊斯兰教义，采用传统教义里的行刑方式血腥的镇压他们认为违反伊斯兰教义的人或者异教徒。它认为自己是即将到来的世界末日的预言者，而且也是首要参与者。它的宗教观点使它作茧自缚从根本上无法进行某些变革，即使这种变革能确保其生存。&lt;BR&gt;<br/>
&lt;P&gt;　　自杀还是他杀？&lt;BR&gt;<br/>
&lt;P&gt;　　最新的一项调查报告反映，世界主要的穆斯林国家对ISIS的态度大概分成了三个层级：&lt;BR&gt;<br/>
&lt;P&gt;　　以黎巴嫩、以色列、约旦、巴勒斯坦为代表的国家强烈反对ISIS。在黎巴嫩，无论是什叶派穆斯林还是逊尼派穆斯林，超过98%的人对ISIS没有好感；以色列91%的阿拉伯人蔑视ISIS；巴勒斯坦领土内84%的人不喜欢ISIS，无论是在加沙地带还是在西岸。对ISIS有不同意见，但负面看法没那么强烈的国家有印度尼西亚、土耳其、尼日利亚、马来西亚和塞内加尔。对ISIS最有好感的是巴基斯坦，只有28%的人对ISIS评价负面，62%的人对极端组织没有意见。&lt;BR&gt;<br/>
&lt;P&gt;　　而这份报告中并没有提及沙特（伊朗除外--本身就是敌视伊斯兰国的什叶派国家），从本质而言ISIS是瓦哈比主义运动的变种。做为瓦哈比主义的始作俑者。沙特王室一直是瓦哈比主义的推广和代言人，沙特政权的合法性更是根深蒂固的植深于瓦哈比主义。沙特王室能统治到今天恰恰是和宗教势力相互利用和相互妥协的结果。&lt;BR&gt;<br/>
&lt;P&gt;　　多年以来，沙特为了维持其在伊斯兰世界的话语权和维护逊尼派穆斯林的地位，长期对外输出瓦哈比主义，试图以宗教达到领导伊斯兰世界。这也是沙特财团对ISIS背后支援的原因之一，然而ISIS相对于瓦哈比主义运动有着更深刻的理解和执行，而沙特不可能回到伊斯兰哈里发统治的时代，这也是跟ISIS在教义理解上最大的分歧。&lt;BR&gt;<br/>
&lt;P&gt;　　伊斯兰世界各国对ISIS意识形态的态度分化代表对不同教义的理解，而近期ISIS几近疯狂制造的巴黎恐怖袭击、黎巴自杀性嫩爆炸案、俄罗斯客机被炸、中国挪威人质被杀等都加剧了ISIS在意识形态孤立，从而直接导致了ISIS在伊斯兰世界的生存危机。&lt;BR&gt;<br/>
&lt;P&gt;　　近期印度尼西亚首先对伊斯兰国在意识形态领域发声，也说明了长久以来印尼受极端思想危害的不安和担忧，与ISIS撇清在意识形态的关系，有助于和解伊斯兰和西方的关系。更预示着伊斯兰世界对ISIS挑起的所谓“文明的冲突“战争的反思，一场由大国博弈引起的代理人战争不能绑架伊斯兰与西方国家的对立，从而也预示着ISIS在意识形态领域的灭顶之灾。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>意识形态;瓦哈比;伊斯兰世界;沙特;教义;伊斯兰国;印度尼西亚;主义</KeyWords><br/><br/>
<vAbstract>伊斯兰世界各国对ISIS意识形态的态度分化代表对不同教义的理解，而近期ISIS几近疯狂制造的巴黎恐怖袭击、黎巴自杀性嫩爆炸案、俄罗斯客机被炸、中国挪威人质被杀等都加剧了ISIS在意识形态孤立，从而直接导致了ISIS在伊斯兰世界的生存危机。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.02 15:33:58</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281516876110960</SID><br/><br/>
<URLID>281516876110960</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://global.dwnews.com/news/2015-12-02/59700097.html</URLName><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>法驻华记者遭北京点名声讨 西方记协发飙</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2015.12.02 15:32:05</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 14:31:02</URLTime><br/><br/>
<URLSize>773</URLSize><br/><br/>
<URLTopic>法驻华记者遭北京点名声讨 西方记协发飙</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　日前，一名驻华法国记者因报道称中国政府将东突与极端组织“伊斯兰国”等同视之的做法是混淆视听，遭到中国官媒点名声讨。对此，北京外国人记者协会提出异议，称这是人身攻击和干涉新闻报道自由的行径。&lt;BR&gt;<br/>
&lt;P&gt;　　据NHK在线新闻12月2日报道，法国一名叫高洁(法文原名为Ursula Gauthier)的记者，11月18日在周刊《新观察家》上发表长篇文章，对中国关于莫在反恐问题上搞双重标准的呼吁，进行了观点完全对立的评述，嘲讽中国向法国表示同情时塞进“私货”，即要求国际社会将东突与“伊斯兰国”（ISIS）等同视之。&lt;BR&gt;<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281516876110960_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;土耳其等国家公开声援东突&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　文章对中国政府的民族政策进行了严词激烈的抨击，认为中国新疆的民族压制手段无理，明确宣称“新疆暴力更多的是由于受到无情的镇压”。&lt;BR&gt;<br/>
&lt;P&gt;　　高洁2014年3月还曾发表一篇文章，描述她作为特派记者在新疆的所见所闻，其中也有大量宣扬新疆如何遭到民族压制政策之苦的内容。对此，中国官方媒体进行了点名批驳，指斥高洁的报道歪曲事实，偏见严重。并且中国的网络上出现针对高洁的恐吓性文字，称“希望这位法国女记者，怀孕时被暴恐分子开膛破肚”。&lt;BR&gt;<br/>
&lt;P&gt;　　对此，外国人记者协会29日发表声明，认为点名痛斥超越了限度，同时不再更新高洁年底到期的在华签证，也属于胁迫。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>点名;高洁;外国人记者协会;声讨;维新;中国政府;新疆;文章</KeyWords><br/><br/>
<vAbstract>土耳其等国家公开声援东突文章对中国政府的民族政策进行了严词激烈的抨击，认为中国新疆的民族压制手段无理，明确宣称&amp;ldquo.对此，外国人记者协会29日发表声明，认为点名痛斥超越了限度，同时不再更新高洁年底到期的在华签证，也属于胁迫。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.02 15:36:47</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281524803962303</SID><br/><br/>
<URLID>281524803962303</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://global.dwnews.com/news/2015-12-02/59700206.html</URLName><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>失事马航残骸竟遭网拍 涉事荷兰警察被逮捕</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2015.12.03 06:32:02</LastTime><br/><br/>
<URLDate>2015.12.02</URLDate><br/><br/>
<URLTime>2015.12.02 20:15:18</URLTime><br/><br/>
<URLSize>604</URLSize><br/><br/>
<URLTopic>失事马航残骸竟遭网拍 涉事荷兰警察被逮捕</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　载有大量荷兰公民的马航MH17被导弹击落事件，已成为荷兰最惨痛的空难而被铭记。但日前，一名荷兰警察竟然在网上拍卖该航班残骸。警方在得到信息后将其逮捕。&lt;BR&gt;<br/>
&lt;P&gt;　　据综合媒体12月2日报道，一名荷兰警察在拍卖网站Marktplaats上出售飞机残骸、调查员的衣帽、马航的纸巾，并声称这些物品与MH17有关。消息曝光后，网站上的相关信息很快被下架，Marktplaats发言人对此表示，在网站上拍卖这些东西是“令人讨厌而不道德的”。&lt;BR&gt;<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281524803962303_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;MH17惨剧制造者依然逍遥法外&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　报道指出，广告虽然已被下架，但警方正在调查时，已有商品售出，而该警察在接受讯问后，已于11月29日被批捕。&lt;BR&gt;<br/>
&lt;P&gt;　　据悉，2014年7月中旬，马来西亚航空由阿姆斯特丹飞往吉隆坡的MH17班机在乌克兰上方遭导弹击落，机上298名乘客全数罹难的悲剧。时至今日，仍没有任何组织声称对此事负责。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>残骸;荷兰警察;网站;乌克兰;逮捕;拍卖;土耳其;战斗机</KeyWords><br/><br/>
<vAbstract>消息曝光后，网站上的相关信息很快被下架， Marktplaats发言人对此表示，在网站上拍卖这些东西是&amp;ldquo.美东时间2015年12月1日美媒关键词：人民币入SDR、巴黎气候变化大会、习近平访问非洲、中非合作论坛、北京雾霾、乌克兰危机、美国2016年总统大选。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.03 07:07:33</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281524801338429</SID><br/><br/>
<URLID>281524801338429</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://global.dwnews.com/news/2015-12-02/59700218.html</URLName><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>掀翻牌桌 普京非常手段逼美国出局</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2015.12.03 06:32:03</LastTime><br/><br/>
<URLDate>2015.12.03</URLDate><br/><br/>
<URLTime>2015.12.03 01:37:48</URLTime><br/><br/>
<URLSize>1575</URLSize><br/><br/>
<URLTopic>掀翻牌桌 普京非常手段逼美国出局</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　俄罗斯连日来对土耳其紧咬不放。除政治、军事、经济报复措施，普京（Vladimir Putin）日前高调抛出土耳其与“伊斯兰国”（ISIS）存在石油交易“黑幕”。不仅与包括美国、以色列、约旦等国进行会面的多个双边乃至于多边场合提及此事。当地时间12月2日15时，俄国防指控中心专门召开主题为“打击国际恐怖主义的俄罗斯武装力量新数据”的国内外媒体吹风会，亦被可能包括提供土耳其“资恐”新证据。&lt;BR&gt;<br/>
&lt;P&gt;　　众所周知，本身经济存在问题的俄罗斯对土耳其采取经济制裁占不到任何便宜，在打击ISIS问题上以及中东局势上俄罗斯面临的难题关键并非土耳其。缘何俄罗斯紧抓土耳其不放？刨根问底追究土耳其与ISIS的关系是何用意？&lt;BR&gt;<br/>
&lt;P&gt;　　1月30日普京认定土耳其为极端组织“伊斯兰国”出售石油提供便利。土总统埃尔多安(Recep Tayyip Erdogan)公开表态，如果事实真如普京所言，自己就下台。12月1日埃尔多安呛声普京：“我公开地说，如果这一事实确定的话，我将不会留在自己的位置上。反之，我要问一下尊敬的普京，你是否留任？”目前的局势似乎变成了普京下台还是埃尔多安下台的口水仗。&lt;BR&gt;<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281524801338429_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;埃尔多安逼问普京：我赶下台，你敢吗&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　土耳其暗勾ISIS 是不争的事实。2013年包括ISIS在内的极端主义组织逐渐在叛乱浪潮中兴起，土耳其一方面继续在西方盟友面前表明“温和”立场，担任反叙利亚阿萨德政府的领头羊，在另一方面，却也开始偷偷支持ISIS这样的极端主义组织。有明确的消息显示，美军在击毙“伊斯兰国”负责石油走私的头目阿布•萨伊夫时，曾找到很多文件，这些文件显示土耳其和ISIS有密切的经济往来。&lt;BR&gt;<br/>
&lt;P&gt;　　土耳其虽于2014年10月2日通过决议，授权军队进入伊拉克和叙利亚打击ISIS，但目标却瞄准了一直抵抗ISIS扩张的库尔德人。且本着“敌人的敌人是朋友”的原则，土耳其为了自己的地缘战略目的，更故意放松土叙边境管理，纵容石油走私。无论土耳其政府是否“知道”或“参与”ISIS的石油生意，其在这样一种黑市石油贸易中起到了关键作用却不容置疑。ISIS的石油输出的一大港口恰恰是土耳其位于地中海的杰伊汉（Ceyhan）。&lt;BR&gt;<br/>
&lt;P&gt;　　但ISIS尚未发迹之时，美欧及包括沙特在内的诸多国家也都曾因反对阿萨德政权，将ISIS视为“叙利亚温和反对派”进行过或多或少的支持。&lt;BR&gt;<br/>
&lt;P&gt;　　前中央情情报局分析师菲利浦·杰拉迪在2011年12月就已提出，“北约已秘密介入叙利亚冲突，土耳其率先成为美国的代理人……北约的秘密战争运输机已抵达位于边境城市伊斯肯德伦的土耳其军事基地，送去了取自利比亚强人卡扎菲晚期军火库的武器，以及利比亚全国过渡委员会的志愿者。”&lt;BR&gt;<br/>
&lt;P&gt;　　“伊斯肯德伦也是叙利亚反对派的根据地，法国和英国的特种部队训练员协助训练叙利亚武装反政府组织，美国中央情报局和美国特种部队提供通信设备和情报，使得反政府军的战斗人员能避免叙利亚政府军集结兵力。”叙利亚反对派不仅在临近叙利亚边境的土耳其军事基地和土耳其军官一起接受军事训练，还在土耳其境内距土叙边界130千米的阿达纳市建立训练营。土叙边境已被视为西方和部分阿拉伯国家向叙境内走私武器、通信设备、资金以及情报支援的大后方。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>普京;土耳其;叙利亚;石油;军事基地;边境;通信设备;维新</KeyWords><br/><br/>
<vAbstract>北约的秘密战争运输机已抵达位于边境城市伊斯肯德伦的土耳其军事基地，送去了取自利比亚强人卡扎菲晚期军火库的武器，以及利比亚全国过渡委员会的志愿者。土叙边境已被视为西方和部分阿拉伯国家向叙境内走私武器、通信设备、资金以及情报支援的大后方。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.03 07:08:11</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281524801665834</SID><br/><br/>
<URLID>281524801665834</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://sputniknews.cn/politics/20151203/1017230947.html</URLName><br/><br/>
<SiteName>俄新网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>俄罗斯将向联合国提供有关“伊斯兰国”向土耳其走私石油的证据</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>俄新网</SRCName><br/><br/>
<LastTime>2015.12.03 06:32:04</LastTime><br/><br/>
<URLDate>2015.12.03</URLDate><br/><br/>
<URLTime>2015.12.03 06:30:49</URLTime><br/><br/>
<URLSize>410</URLSize><br/><br/>
<URLTopic>俄罗斯将向联合国提供有关“伊斯兰国”向土耳其走私石油的证据</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　<br/>