<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TRS [
<!ELEMENT TRS (REC)>
<!ELEMENT REC (SID,URLID,StartID,AttachID,PURLID,URLName,SiteName,Channel,URLTitle,GroupName,SRCName1,SRCName2,SRCName,LastTime,URLDate,URLTime,URLSize,URLTopic,ContentType,CharSet,Catalog1,Catalog2,Catalog,SimFlag,SimRank,TableFlag,ImageFlag,Content,URLTable,URLImage,PageLevel,PageRank,Authors,KeyWords,vAbstract,Urgency,SrcType,DocFormat,AttachSize,Attachment,URLBody,Receiver,CC,Infotype,Doccatalog,Modifyuser,Importance,Confid,Istop,Isrelease,Istrash,DelFlag,ReleaseTime,Label,status,CIS3C,CIS3D,CIS3P,CIS3N,CIS3B,CIS3T,ADDTIME,br)>
<!ELEMENT SID (#PCDATA | br)*>
<!ELEMENT URLID (#PCDATA | br)*>
<!ELEMENT StartID (#PCDATA | br)*>
<!ELEMENT AttachID (#PCDATA | br)*>
<!ELEMENT PURLID (#PCDATA | br)*>
<!ELEMENT URLName (#PCDATA | br)*>
<!ELEMENT SiteName (#PCDATA | br)*>
<!ELEMENT Channel (#PCDATA | br)*>
<!ELEMENT URLTitle (#PCDATA | br)*>
<!ELEMENT GroupName (#PCDATA | br)*>
<!ELEMENT SRCName1 (#PCDATA | br)*>
<!ELEMENT SRCName2 (#PCDATA | br)*>
<!ELEMENT SRCName (#PCDATA | br)*>
<!ELEMENT LastTime (#PCDATA | br)*>
<!ELEMENT URLDate (#PCDATA | br)*>
<!ELEMENT URLTime (#PCDATA | br)*>
<!ELEMENT URLSize (#PCDATA | br)*>
<!ELEMENT URLTopic (#PCDATA | br)*>
<!ELEMENT ContentType (#PCDATA | br)*>
<!ELEMENT CharSet (#PCDATA | br)*>
<!ELEMENT Catalog1 (#PCDATA | br)*>
<!ELEMENT Catalog2 (#PCDATA | br)*>
<!ELEMENT Catalog (#PCDATA | br)*>
<!ELEMENT SimFlag (#PCDATA | br)*>
<!ELEMENT SimRank (#PCDATA | br)*>
<!ELEMENT TableFlag (#PCDATA | br)*>
<!ELEMENT ImageFlag (#PCDATA | br)*>
<!ELEMENT Content (#PCDATA | br)*>
<!ELEMENT URLTable (#PCDATA | br)*>
<!ELEMENT URLImage (#PCDATA | br)*>
<!ELEMENT PageLevel (#PCDATA | br)*>
<!ELEMENT PageRank (#PCDATA | br)*>
<!ELEMENT Authors (#PCDATA | br)*>
<!ELEMENT KeyWords (#PCDATA | br)*>
<!ELEMENT vAbstract (#PCDATA | br)*>
<!ELEMENT Urgency (#PCDATA | br)*>
<!ELEMENT SrcType (#PCDATA | br)*>
<!ELEMENT DocFormat (#PCDATA | br)*>
<!ELEMENT AttachSize (#PCDATA | br)*>
<!ELEMENT Attachment (#PCDATA | br)*>
<!ELEMENT URLBody (#PCDATA | br)*>
<!ELEMENT Receiver (#PCDATA | br)*>
<!ELEMENT CC (#PCDATA | br)*>
<!ELEMENT Infotype (#PCDATA | br)*>
<!ELEMENT Doccatalog (#PCDATA | br)*>
<!ELEMENT Modifyuser (#PCDATA | br)*>
<!ELEMENT Importance (#PCDATA | br)*>
<!ELEMENT Confid (#PCDATA | br)*>
<!ELEMENT Istop (#PCDATA | br)*>
<!ELEMENT Isrelease (#PCDATA | br)*>
<!ELEMENT Istrash (#PCDATA | br)*>
<!ELEMENT DelFlag (#PCDATA | br)*>
<!ELEMENT ReleaseTime (#PCDATA | br)*>
<!ELEMENT Label (#PCDATA | br)*>
<!ELEMENT status (#PCDATA | br)*>
<!ELEMENT CIS3C (#PCDATA | br)*>
<!ELEMENT CIS3D (#PCDATA | br)*>
<!ELEMENT CIS3P (#PCDATA | br)*>
<!ELEMENT CIS3N (#PCDATA | br)*>
<!ELEMENT CIS3B (#PCDATA | br)*>
<!ELEMENT CIS3T (#PCDATA | br)*>
<!ELEMENT ADDTIME (#PCDATA | br)*>
<!ELEMENT br EMPTY>
]>
<TRS>
<REC>
<SID>281532728013133</SID><br/><br/>
<URLID>281532728013133</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://bj.crntt.com/doc/1040/5/8/1/104058197.html?coluid=148&amp;kindid=7550&amp;docid=104058197&amp;mdate=1225105428</URLName><br/><br/>
<SiteName>中评网</SiteName><br/><br/>
<URLTitle>美国称中国反恐主义草案“弊大于利”</URLTitle><br/><br/>
<GroupName>测试</GroupName><br/><br/>
<SRCName>中评网</SRCName><br/><br/>
<LastTime>2015.12.25 12:47:37</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 10:54:28</URLTime><br/><br/>
<URLSize>602</URLSize><br/><br/>
<URLTopic>美国称中国反恐主义草案“弊大于利”</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　2015年，全球反恐形势异常严峻，恐怖主义威胁着世界安宁与稳定。就在世界多数国家取得反恐国际合作共识的时候，美国国务院近日却妄议中国反恐怖主义法草案，再次在反恐问题上搞双重标准。<br/>
&lt;P&gt;　　美国国务院妄称中国反恐怖主义法草案对打击恐怖主义“弊大于利”。这不是美国政府第一次无端指责中国的反恐法，也不是第一次妄议中国的国内法。对于任何一个主权国家，立法都属于国家内政，他国无权说三道四。更何况，美国的妄议有着不可告人的目的。&lt;BR&gt;<br/>
&lt;P&gt;　　事实胜于雄辩。美国此次主要拿三个方面说事：一是担心中国的反恐法影响美对华贸易和投资，二称该法案会限制中国的言论、集会和宗教自由，三称该法案将损害网络信息安全。真相到底如何呢，我们让事实来说话。&lt;BR&gt;<br/>
&lt;P&gt;　　其一、中国多次强调，对外开放是中国的基本国策，中国利用外资的政策不会变，对外商投资企业合法权益的保障不会变，为各国企业在华投资兴业提供更好服务的方向不会变。根据2015年发布的《世界投资报告》，中国在2014年已经成为全球吸引直接投资最多的国家。&lt;BR&gt;<br/>
&lt;P&gt;　　单看中美两国之间，2014年，中国新批设立美资企业1176家，对华投资项目累计超过6.4万个，实际投入754亿美元。此外，美国商务部公布的国际贸易数据显示，今年1至9月，中美货物贸易额达到4416亿美元。这是自1985年以来，中国首次成为美国最大的贸易伙伴。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>中国;美国;弊大于利;投资;草案;信息安全;贸易伙伴;合法权益</KeyWords><br/><br/>
<vAbstract>其一、中国多次强调，对外开放是中国的基本国策，中国利用外资的政策不会变，对外商投资企业合法权益的保障不会变，为各国企业在华投资兴业提供更好服务的方向不会变。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 13:36:08</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281532628665983</SID><br/><br/>
<URLID>281532628665983</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://cn.reuters.com/article/mideast-crisis-usa-assad-idCNKBS0U807120151225</URLName><br/><br/>
<SiteName>路透社</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>美国曾与叙利亚政府官员秘密沟通</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>路透社</SRCName><br/><br/>
<LastTime>2015.12.25 12:36:10</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 12:34:20</URLTime><br/><br/>
<URLSize>659</URLSize><br/><br/>
<URLTopic>美国曾与叙利亚政府官员秘密沟通</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;<br/>
&lt;P&gt;　　周四报道称，美国官员曾与叙利亚政府官员秘密沟通以寻求限制叙利亚的暴力活动，还曾在2011年寻求鼓励在叙利亚进行军事政变。<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　报道援引对包括美国现任及前任官员在内的二十几人的采访称，美国情报官员确认了可能领导政变的军方官员，后者来自叙利亚少数派阿拉维派，但美方发现这些人鲜有弱点可以利用。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　报道称，当时，叙利亚政府开始镇压抗议活动且有士兵开始逃离军队。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　“2011年，白宫的政策是寻找叙利亚政权内部的机会，提供激励措施促使民众背弃阿萨德，以在叙利亚促成演变。”报导援引一位前政府高官的话称。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　报道称，奥巴马政府在2012年调整政策，停止了试图影响阿萨德政府的努力，转而支持叙利亚反对派力量。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　报道称，美国和叙利亚的高官曾经直接对话，还曾通过包括俄罗斯和伊朗在内的第三方传递信息。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　美国官员对该报称，美国前副国务卿伯恩斯（William Burns）曾与叙利亚外长穆阿利姆（Walid al-Moallem）两次通电话，以警告阿萨德政府勿大规模使用化学武器。伯恩斯去年离任。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　一位美国高官称，美国同叙利亚的秘密沟通与同古巴或伊朗进行的沟通不同，而是更多地聚焦具体问题。&lt;BR&gt;<br/>
&lt;P&gt;<br/>
&lt;P&gt;　　“我们曾多次表示：如果你们停止使用炸弹桶，就能为停火创造更好的条件。”一位美国高官对该报称。　&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>美国;叙利亚政府;官员;秘密;报道称;伯恩斯;沟通;经济增长</KeyWords><br/><br/>
<vAbstract>“资产荒”引发信用债配置热情更多路透资讯中国航母部队战斗力建设取得明显进步--解放军报印度总理莫迪访问俄罗斯两国加强能源及防务合作沙特一医院发生火灾至少24人死亡（更新版）伊朗呼吁中国加入打击伊斯兰国西方多国发布安全警报北京警方启动黄色预警多媒体新闻图片新闻。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 13:39:52</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>61876569</SID><br/><br/>
<URLID>61876569</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>VOA</SiteName><br/><br/>
<URLTitle>美国南部龙卷风造成至少14人死亡</URLTitle><br/><br/>
<SRCName>VOA</SRCName><br/><br/>
<LastTime>2015.12.25 10:50:02</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 15:33:02</URLTime><br/><br/>
<URLSize>421</URLSize><br/><br/>
<URLTopic>美国南部龙卷风造成至少14人死亡</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　美国南部和中西部出现罕见的12月龙卷风，数百个家庭失去房屋，将在紧急避难所度过圣诞节。&lt;BR&gt;<br/>
&lt;P&gt;　　自星期三以来，强风暴导致至少14人丧生，密西西比州州长布莱恩特宣布几个县进入紧急状态。&lt;BR&gt;<br/>
&lt;P&gt;　　在北至密西根州的地区发生10数起龙卷风，摧毁或严重破坏了房屋和商业。&lt;BR&gt;<br/>
&lt;P&gt;　　密西西比州据报有7人死亡，田纳西州和阿肯色州分别有6人和1人丧生。&lt;BR&gt;<br/>
&lt;P&gt;　　在美国东部地区，主要城市纽约、华盛顿和费城下雨不停，最高气温则达到创纪录的摄氏22度，圣诞前夜这天感觉更像是春天。&lt;BR&gt;<br/>
&lt;P&gt;　　任何期待一个白色圣诞节的人只能前往美国西北部，天气预报说，华盛顿州、俄勒冈州、内华达州和北加州天气寒冷，并有大雪。&lt;BR&gt;<br/>
&lt;P&gt;　　美国政府专家说，被称为厄尔尼诺的气候模式是美国大部分地区出现异常高温及恶劣天气的部分原因。&lt;SPAN title=G151225154444&gt;.&lt;/SPAN&gt;&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>cjj</Authors><br/><br/>
<KeyWords>龙卷风;死亡;美国南部;密西西比州;厄尔尼诺;强风暴;房屋;天气</KeyWords><br/><br/>
<vAbstract>美国南部和中西部出现罕见的12月龙卷风，数百个家庭失去房屋，将在紧急避难所度过圣诞节。</vAbstract><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 10:50:02</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>84713116</SID><br/><br/>
<URLID>84713116</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>环球网</SiteName><br/><br/>
<URLTitle>奥巴马政府计划驱逐非法移民 引民主党竞选人围攻</URLTitle><br/><br/>
<SRCName>环球网</SRCName><br/><br/>
<LastTime>2015.12.25 16:12:32</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 16:11:57</URLTime><br/><br/>
<URLSize>685</URLSize><br/><br/>
<URLTopic>奥巴马政府计划驱逐非法移民 引民主党竞选人围攻</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　据英国路透社12月24日报道，美国国土安全部日前计划于2016年在全国范围内开展驱逐非法移民的行动。此计划一出，立即就引发 美国国内的激烈辩论。美国民主党候选人们对此计划表示强烈的反对。&lt;/P&gt;<br/>
&lt;P&gt;　　美联社24日援引《华盛顿邮报》的消息称，非法移民驱逐行动将由美国国土安全部下属的移民和海关执法局执行，行动将于2016年1月启动，其目标除了驱逐未登记的非法移民外，还将涉及2014年以来抵达美国的数百名逃离中美洲动乱的难民。&lt;/P&gt;<br/>
&lt;P&gt;　　尽管移民和海关执法局发言人不愿透露该计划的细节，但他表示此次行动的目标是“威胁国家、公众和边境安全”的非法移民，包括“被发现企图非法进入美国或自2014年以来已被下令遣返的个人”，而且不论目标“是一个人或是有其他家庭成员”，将一律驱逐出境。&lt;/P&gt;<br/>
&lt;DIV id=adPp class=&quot;ad250x250 fLeft marRig10&quot;&gt;&lt;/DIV&gt;<br/>
&lt;P&gt;　　据路透社报道，此计划一出，美国民主党总统竞选人和人权组织就将炮火对准了奥巴马政府。 &lt;/P&gt;<br/>
&lt;P&gt;　　目前领跑民主党总统竞选的希拉里•克林顿表示她对相关报道感到“十分担忧”，“每个人都应该享有完整公平的申辩权，每个有需要的人都应当享有我们国家给予的庇护，这一点至关重要。” &lt;/P&gt;<br/>
&lt;P&gt;　　希拉里最大竞争对手伯尼•桑德斯在一份声明中说道：“我们的国家一直被视作引航的灯塔、受压迫者的安全港……我们应该做的，是庇护这些寻求庇护的儿童和家庭，而不是将他们扫地出门。”此外，还有一些民主党人士在社交网络上对这一计划表示谴责。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wyj</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 16:12:32</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>49293635</SID><br/><br/>
<URLID>49293635</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>环球网</SiteName><br/><br/>
<URLTitle>美国曾试图寻找叙总统的“薄弱环节”以迫使其下台</URLTitle><br/><br/>
<SRCName>环球网</SRCName><br/><br/>
<LastTime>2015.12.25 16:11:57</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 16:11:26</URLTime><br/><br/>
<URLSize>524</URLSize><br/><br/>
<URLTopic>美国曾试图寻找叙总统的“薄弱环节”以迫使其下台</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　据俄罗斯新闻频道12月24日消息，美国《华尔街日报》报道称，美国政府曾在数年间试图寻找叙利亚总统巴沙尔•阿萨德的“薄弱环节”，以迫使其辞去总统职位。&lt;/P&gt;<br/>
&lt;P&gt;　　美国《华尔街日报》刊文称，奥巴马政府曾在数年间试图寻找叙利亚总统巴沙尔•阿萨德的“薄弱环节”，以迫使其辞去总统职位。《华尔街日报》刊文如此写道，巴沙尔曾多次尝试与美国政府联络以共同打击恐怖主义。但在2011年，美国总统奥巴马公开呼吁巴沙尔辞去总统职位，且美国从未改变此政策，尽管至今在世界大国中有关巴沙尔是否应辞去总统职务的问题仍在争论中。&lt;/P&gt;<br/>
&lt;P&gt;　　叙利亚巴沙尔政府军与叙利亚民兵从2011年3月开始发生武装冲突。根据联合国数据显示，冲突已造成22万人死亡。其中与政府军作战的有“伊斯兰国”恐怖组织和“努斯拉阵线”恐怖组织。&lt;/P&gt;<br/>
&lt;DIV id=adPp class=&quot;ad250x250 fLeft marRig10&quot;&gt;&lt;/DIV&gt;<br/>
&lt;P&gt;　　12月18日，联合国安理会一致通过有关叙利亚问题的决议，决定从2016年1月开启叙利亚的和平进程。但在相关文件中，并未提到有关巴沙尔的去留问题。俄罗斯主张，叙利亚总统的未来应由叙利亚人民来决定。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wyj</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 16:11:57</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>19050830</SID><br/><br/>
<URLID>19050830</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>中新网</SiteName><br/><br/>
<URLTitle>美国康州小学枪案周年 奥巴马夫妇将在白宫默哀</URLTitle><br/><br/>
<SRCName>中新网</SRCName><br/><br/>
<LastTime>2015.12.25 16:11:26</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 16:10:04</URLTime><br/><br/>
<URLSize>605</URLSize><br/><br/>
<URLTopic>美国康州小学枪案周年 奥巴马夫妇将在白宫默哀</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 据美国媒体报道，在康州纽顿镇桑迪虎胡克小学发生枪击案近一周年之际，美国副总统拜登10日宣布一项1亿美元的政府资助计划，以扩大精神治疗服务。&lt;/P&gt;<br/>
&lt;P&gt;　　纽顿镇小学的血案发生后，拜登会晤了受害者家人和精神疾病治疗人员，积极推动奥巴马政府的从严限枪措施。他在10日的声明中说：“全国接受精神健康诊治的儿童还不到一半，这是不能忍受的。”&lt;/P&gt;<br/>
&lt;P&gt;　　美国总统奥巴马表示，纽顿镇去年12月14日的枪案，是他总统任内最暗淡的一天。康州检察长上月公布枪案调查，没有查清枪手的作案动机，不知道20岁的蓝萨为何开枪滥杀。&lt;/P&gt;<br/>
&lt;P&gt;　　白宫官员说，在14日的血案周年之际，奥巴马和第一夫人米歇尔将在白宫默哀，以悼念受害人。&lt;/P&gt;<br/>
&lt;P&gt;　　血案发生后，奥巴马和拜登主张扩大对购枪人的背景调查，禁售威力强大的攻击性武器，并限制大容量的弹夹。但在全国枪支协会的强大游说下，国会没有通过限枪法案。&lt;/P&gt;<br/>
&lt;P&gt;　　白宫建议拨出1.3亿美元，以帮助教师和与儿童打交道的人，及早发现精神病患的征兆，并帮助他们治疗，但国会仍没拨出专款。&lt;/P&gt;<br/>
&lt;P&gt;　　奥巴马政府将从卫生与福利部的预算中拨出5000万美元，帮助社区卫生部门聘请精神健康专家，另一半的5000万美元来自农业部的预算，要改善乡村地区治疗精神疾病的设施。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wyj</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 16:11:26</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>32394826</SID><br/><br/>
<URLID>32394826</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>中新网</SiteName><br/><br/>
<URLTitle>奥巴马提名两名竞选支持者为美国驻外大使</URLTitle><br/><br/>
<SRCName>中新网</SRCName><br/><br/>
<LastTime>2015.12.25 16:13:54</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 16:13:27</URLTime><br/><br/>
<URLSize>298</URLSize><br/><br/>
<URLTopic>奥巴马提名两名竞选支持者为美国驻外大使 </URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　10月30日电据外媒报道，美国总统奥巴马提名了两名在2012年总统竞选中，为他提供有力帮助的支持者为美国驻外大使。&lt;/P&gt;<br/>
&lt;P&gt;　　29日，白宫确认，罗伯特•巴伯(Robert Barber)和马克•吉尔伯特(Mark Gilbert)分别被奥巴马提名为美国驻冰岛和新西兰大使，吉尔伯特此前是芝加哥白袜队的球员。&lt;/P&gt;<br/>
&lt;P&gt;　　这两名候选人此前曾是奥巴马的国家财务团队成员。在奥巴马的总统竞选中，为其募集了超过50万美元的资金。&lt;/P&gt;<br/>
&lt;P&gt;　　今年早些时候，奥巴马提名了他的前政治智囊人员、前竞选财政领袖以及其他一些支持者出任南非、丹麦、西班牙和德国的大使职务。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wyj</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 16:13:54</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>5570323</SID><br/><br/>
<URLID>5570323</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>凤凰网</SiteName><br/><br/>
<URLTitle>美国向俄增购火箭发动机 麦凯恩称是背叛盟友</URLTitle><br/><br/>
<SRCName>凤凰网</SRCName><br/><br/>
<LastTime>2015.12.25 16:13:27</LastTime><br/><br/>
<URLDate>2015.12.25</URLDate><br/><br/>
<URLTime>2015.12.25 16:12:32</URLTime><br/><br/>
<URLSize>897</URLSize><br/><br/>
<URLTopic>美国向俄增购火箭发动机 麦凯恩称是背叛盟友</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;DIV class=&quot;dy_box ss_none&quot;&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 美国洛克希德·马丁公司和波音公司，组建的合资企业，联合发射联盟23日表示，将向俄罗斯增加订购20台RD-180火箭发动机。美公司向俄增订20台火箭发动机联合发射联盟发言人罗伊格称，此前向&lt;/P&gt;<br/>
&lt;DIV class=bg_bottom&gt;&lt;SPAN&gt;&lt;/SPAN&gt;&lt;/DIV&gt;&lt;/DIV&gt;<br/>
&lt;DIV id=main_content class=js_selection_area&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 美国洛克希德·马丁公司和波音公司组建的合资企业联合发射联盟23日表示，将向俄罗斯增加订购20台RD-180火箭发动机。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 联合发射联盟发言人罗伊格称，此前向俄罗斯预订的29台发动机全部到位后，这批新订发动机即刻开始供货。她表示，联合发射联盟今年已经收到了8台RD-180发动机。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 联合发射联盟称，在美国研制出自己的新发动机并完成检测之前，将继续向俄罗斯订购火箭发动机，这些发动机将用于“阿特拉斯5号”火箭的第一级，以向现有及潜在客户提供民用和商业发射服务。有消息称，美国国会已拨款2.2亿美元研制新型国产发动机。但是据英国路透社消息报道，这一进程将十分缓慢，且难以达成。&lt;/P&gt;<br/>
&lt;P&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 去年克里米亚事件发生后，美国国会通过《2015年度美国国防授权法案》，禁止在军事用途中使用俄制发动机。但美国2016年度开支法案取消了发射合同竞标中对发动机原产地的限制。美国共和党参议员麦凯恩表示，美国对俄制火箭发动机购买禁令的解除，将为俄罗斯提供获取数百万美元收益的机会，并指责这一举动是对美国盟友在制裁俄罗斯承诺上的背叛。&lt;/P&gt;&lt;/DIV&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>wyj</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>13</Doccatalog><br/><br/>
<Modifyuser>wyj</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.25 16:13:27</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281537376282973</SID><br/><br/>
<URLID>281537376282973</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://sputniknews.cn/russia/20151226/1017508164.html</URLName><br/><br/>
<SiteName>俄新网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>马特维延科：克里米亚将在明年年末前获得能源独立</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>俄新网</SRCName><br/><br/>
<LastTime>2015.12.26 06:35:24</LastTime><br/><br/>
<URLDate>2015.12.26</URLDate><br/><br/>
<URLTime>2015.12.26 06:33:40</URLTime><br/><br/>
<URLSize>305</URLSize><br/><br/>
<URLTopic>马特维延科：克里米亚将在明年年末前获得能源独立</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　马特维延科星期五在“俄罗斯-24”电视台采访时表示“我认为，在明年年末前，克里米亚与塞瓦斯托波尔将完全地实现能源独立。”&lt;BR&gt;<br/>
&lt;P&gt;　　她指出，为实现这一目标，正在对建设发电站及其他能源设施进行规划，目前正在解决水源和天然气的供给问题。这是保障这些地区发展及活力的领域。&lt;BR&gt;<br/>
&lt;P&gt;　　她表示，此外，最重要且并不轻松的任务是刻赤大桥的建设。俄联邦委员会主席指出，“当这座跨过刻赤海峡大桥的建设完成时，所有交通问题也将迎刃而解。”&lt;BR&gt;<br/>
&lt;P&gt;　　马特维延科强调，“我们应该这样做，以便保障克里米亚及塞瓦斯托波尔完全脱离乌克兰的束缚而独立，并使它们与俄罗斯祖国大陆联结在一起。”&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>马特维延科;克里米亚;能源;塞瓦斯托波尔;发电站;保障;天然气;水源</KeyWords><br/><br/>
<vAbstract>她指出，为实现这一目标，正在对建设发电站及其他能源设施进行规划，目前正在解决水源和天然气的供给问题。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>8</Doccatalog><br/><br/>
<Modifyuser>sy</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.26 07:47:59</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>281537363598558</SID><br/><br/>
<URLID>281537363598558</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<URLName>http://global.dwnews.com/news/2015-12-25/59706006.html</URLName><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<Channel>国际</Channel><br/><br/>
<URLTitle>美国突然扩大对俄制裁：惯性还是惰性</URLTitle><br/><br/>
<GroupName>国际</GroupName><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2015.12.26 06:32:27</LastTime><br/><br/>
<URLDate>2015.12.26</URLDate><br/><br/>
<URLTime>2015.12.26 05:40:28</URLTime><br/><br/>
<URLSize>1405</URLSize><br/><br/>
<URLTopic>美国突然扩大对俄制裁：惯性还是惰性</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　美国近日正式宣布，因俄罗斯没有执行关于乌克兰问题的明斯克协议，决定进一步明确对俄罗斯企业和个人的制裁对象，并在名单中增补了新成员。这则消息给莫斯科罕见的暖冬带来瑟瑟寒意。&lt;BR&gt;<br/>
&lt;P&gt;　　综合媒体12月25日报道，俄罗斯政府反应强烈并研究反击措施。俄罗斯总统新闻秘书佩斯科夫宣布，扩大制裁名单是“不符合逻辑”、“不友好”的举动。他强调，俄方将依据相互对等原则，分析并拟定可能采取的对应措施。反击制裁措施出台的时间等具体的决定，将由总统和政府作出。&lt;BR&gt;<br/>
&lt;P&gt;　　对美国此举出于什么考虑，俄罗斯官员和学者有自己的评判，前者更多地认为是出于惰性，即面对困境中的俄美关系和即将来临的总统选举，最好的选择是不做选择。俄外交部认为，美国这一举措说明，美国不想改善与俄罗斯的关系。&lt;BR&gt;<br/>
&lt;P&gt;　　<br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281537363598558_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;美国扩大制裁令普京极为不爽&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　俄罗斯外交部副部长谢尔盖·里亚布科夫说，“这是条死胡同，两国关系发展到今天的地步，完全是华盛顿的责任。作出这样的决定，说明其决策者根本不想从现状中找到解决问题的出路。这只能说明他们在此问题上顽固不化，对俄方所有的努力置若罔闻。”&lt;BR&gt;<br/>
&lt;P&gt;　　俄罗斯学者则认为这是美国扼制俄罗斯政策的继续，是政策惯性。俄罗斯科学院欧洲研究所副所长谢尔盖·卡拉干诺夫对媒体表示，“对美国举措意外的人，都是此前认为美国会很快改变对俄罗斯政策的人。因为似乎在强硬和压力没有取得效果时，美国曾几次软化政策，而且如果目前与俄罗斯的合作的话，将对美国有利。&lt;BR&gt;<br/>
&lt;P&gt;　　但是，政治是残酷的，美国对俄罗斯的扼制和高压政策几乎没有变化。因为美国和西方期望在俄罗斯经济下降的情况下，俄罗斯早晚会让步的。”其实，美国对俄扩大制裁意在乌克兰。2015年7月31日，美国第一次重新审查对俄罗斯企业和个人的制裁名单。美国财政部官员表示，“此次继续明确制裁名单，正是华盛顿寻找外交途径解决乌克兰危机的政策的一部分。只要俄罗斯一天不履行明斯克协议规定的义务，如向乌克兰归还乌俄边境控制权，美国就不会解除制裁。”&lt;BR&gt;<br/>
&lt;P&gt;　　其次，确保制裁效果与欧洲盟友同步，也是美国扩大制裁的出发点。美国驻俄罗斯使馆新闻官表示，美国没有扩大制裁名单，只是进一步明确此前的制裁目标，“因为这些企业善于规避限制和企图摆脱制裁的影响。为了提高我们相关措施的功效，必须定期明确名单以保障相关措施的有效性。”美国大使馆还强调，这是为了与欧盟保持行动一致，增补进制裁名单的企业和个人已被欧盟纳入了制裁范围，这有益于美国与欧盟的企业按照统一规则和标准做事。&lt;BR&gt;<br/>
&lt;P&gt;　　“入围名单”的俄罗斯外贸银行宣称，进入美国制裁名单不会对银行业务产生负面影响，银行现在不能在美国市场得到借贷，此前也没有相关业务、对银行的客户也没有任何影响，因为银行吸纳的资金完全在俄罗斯市场。所有开户客户都在俄罗斯，所以对他们也没有影响。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<KeyWords>美国;制裁名单;扩大制裁;惰性;欧盟;惯性;俄罗斯政策;乌克兰</KeyWords><br/><br/>
<vAbstract>美国驻俄罗斯使馆新闻官表示，美国没有扩大制裁名单，只是进一步明确此前的制裁目标， &amp;ldquo.美国大使馆还强调，这是为了与欧盟保持行动一致，增补进制裁名单的企业和个人已被欧盟纳入了制裁范围，这有益于美国与欧盟的企业按照统一规则和标准做事。</vAbstract><br/><br/>
<SrcType>0</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>sy</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.26 07:53:20</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>65442504</SID><br/><br/>
<URLID>65442504</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>大纪元</SiteName><br/><br/>
<URLTitle>美国调高H-1B及L-1签证费 印度IT业哗然</URLTitle><br/><br/>
<SRCName>大纪元</SRCName><br/><br/>
<LastTime>2015.12.26 07:29:22</LastTime><br/><br/>
<URLDate>2015.12.26</URLDate><br/><br/>
<URLTime>2015.12.26 07:25:45</URLTime><br/><br/>
<URLSize>1967</URLSize><br/><br/>
<URLTopic>美国调高H-1B及L-1签证费 印度IT业哗然</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>0</TableFlag><br/><br/>
<ImageFlag>0</ImageFlag><br/><br/>
<Content>&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 美国奥巴马总统上周签署总计约1.8万亿美国2016年联邦政府支出及减税的一揽子法案中，包括《扎德罗加9/11健康和赔偿法案》（Zadroga 9/11 Health and Compensation Act，简称“扎德罗加法案”）修正案。依“扎德罗加法案”修正案，今年4月1日以后，IT企业为员工申请美国H-1B以及L-1的签证费将翻倍。由于印度IT产业是H-1B签证的主要使用者，此举已引起印度政府及IT产业的关注。&lt;BR&gt;<br/>
&lt;P&gt;　　综合外媒报导，依“扎德罗加法案”修正案，员工人数超过50人且50%以上的员工持有H-1B以及L-1签证的IT公司，自今年4月1日起申请H-1B及L-1签证的费用，将分别由2,000美元提高到4,000美元，以及2,250美元调高到4,500美元，效期为10年。美国行政部门所收取的H-1B及L-1签证申请费，将用于支应生物识别出入境追踪系统以及911救难人员的健康检查和治疗等所需的支出。&lt;BR&gt;<br/>
&lt;P&gt;　　印度各界反应&lt;BR&gt;<br/>
&lt;P&gt;　　Financial Express的报导，由于美国是印度IT产业的最大市场，因此H-1B及L-1签证申请费提高，对印度IT产业将造成不小的影响，例如印度的Tata Consultancy Services公司，美国市场的营收占其总收入的51%，Infosys公司则为63%。&lt;BR&gt;<br/>
&lt;P&gt;　　值得注意的是，早先的H-1B签证申请费仅325美元。过去十年美国行政部门增加与H-1B签证有关的费用，加上本次“扎德罗加法案”修正案调高的签证申请费，估计印度IT公司自今年4月1日开始申请每份H1-B签证所需支付的费用总计将高达8,000美元到10,000美元之间。&lt;BR&gt;<br/>
&lt;P&gt;　　印度工商协会（Federation of Indian Chambers of Commerce and Industry, FICCI）在一份声明中表示，“扎德罗加法案”涉及的健康及边境安全议题，完全与IT产业无关，将两者连结对IT产业不公平。签证申请费的提高不仅冲击印度IT产业，同时也限制美国企业聘雇海外IT专业人才，使美国企业被迫移到海外，进而减少美国的就业机会及税收。&lt;BR&gt;<br/>
&lt;P&gt;　　印度软体和服务业企业行业协会（National Association of Software and Services Companies, NASSCOM）预估，签证申请费的调高将使印度IT产业每年增加约4亿美元的支出。&lt;BR&gt;<br/>
&lt;P&gt;　　根据NASSCOM的报告显示，印度科技业在美国2011年到2015年的财年总计缴税金额达225亿美元、2011年到2013财年的投资金额达20亿美元、2014年财年直接或间接支持美国41.1万个工作机会。&lt;BR&gt;<br/>
&lt;P&gt;　　The Hindu报导，今年的65,000个H-1B签证名额在4月1日开始后数天即已用完。事实上由于收到的H-1B签证远超过年度名额，因为美国行政部门不得不采取计算机程式抽签的方式。&lt;BR&gt;<br/>
&lt;P&gt;　　H-1B签证及L-1签证&lt;BR&gt;<br/>
&lt;P&gt;　　H-1B工作签证是一种非移民签证，允许美国雇主临时聘用外籍专业技术人员，为美国的经济作出宝贵贡献。H-1B签证提供外籍专业技术人员在美国合法居住和工作的机会，外籍专业技术人员可在美国连续居住6年，并允许配偶及子女（未满21岁），陪他们在美国合法居住。&lt;BR&gt;<br/>
&lt;P&gt;　　在H-1B申请过程中，雇主为申请人，外籍员工为受益人。外籍员工个人不能为自己申请H-1B签证。该外籍员工最低必须拥有学士学位或者同等学历。符合H-1B签证的职业通常需要专业化的知识，其包括但不限于：IT、建筑、工程、数学、物理科学研究、社会科学、生物技术、医疗保健/医药、教育、法律、会计、商业、神学、艺术、电脑、财务、会计、金融、市场行销、销售、招聘和电信。&lt;BR&gt;<br/>
&lt;P&gt;　　L-1签证是非移民工作签证，在美国及海外都有商业机构的跨国公司，在派遣美国以外国家分公司的高级经理、行政主管、或拥有特殊知识的专业技术人员去美国分公司工作时，可以为员工申请L-1签证。&lt;BR&gt;<br/>
&lt;P&gt;　　在L-1签证申请过程中，跨国公司是L-1签证的申请人，外籍高级行政管理人员或专业技术人员是L-1签证的受益人。L1签证的受益人在提交L-1签证申请之前的三年内，必须在其作为申请人的跨国公司的海外机构（非美国境内机构）连续工作一年以上。该跨国公司在海外的机构必须和在美国的机构属于母子公司，分公司或者附属公司的关系，并且有实际的资金和业务的来往。L1跨国公司还可以包括非营利性、宗教、或慈善机构。&lt;BR&gt;&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>sy</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>
<Infotype>1</Infotype><br/><br/>
<Doccatalog>23</Doccatalog><br/><br/>
<Modifyuser>sy</Modifyuser><br/><br/>
<Importance>1</Importance><br/><br/>
<Confid>1</Confid><br/><br/>
<Istop>0</Istop><br/><br/>
<Isrelease>0</Isrelease><br/><br/>
<Istrash>0</Istrash><br/><br/>
<ReleaseTime>2015.12.26 07:29:22</ReleaseTime><br/><br/>
<CIS3T>2000.01.01</CIS3T><br/><br/>
</REC>

<REC>
<SID>68667307</SID><br/><br/>
<URLID>68667307</URLID><br/><br/>
<StartID>0</StartID><br/><br/>
<PURLID>0</PURLID><br/><br/>
<SiteName>多维新闻网</SiteName><br/><br/>
<URLTitle>奥巴马同普京的幕后沟通逐渐曝光</URLTitle><br/><br/>
<SRCName>多维新闻网</SRCName><br/><br/>
<LastTime>2015.12.26 07:42:51</LastTime><br/><br/>
<URLDate>2015.12.26</URLDate><br/><br/>
<URLTime>2015.12.26 07:42:24</URLTime><br/><br/>
<URLSize>1700</URLSize><br/><br/>
<URLTopic>奥巴马同普京的幕后沟通逐渐曝光</URLTopic><br/><br/>
<SimFlag>0</SimFlag><br/><br/>
<SimRank>0</SimRank><br/><br/>
<TableFlag>1</TableFlag><br/><br/>
<ImageFlag>1</ImageFlag><br/><br/>
<Content>&lt;P&gt;　　奥巴马总统任期还剩下一年时间，如果盘点其任内最大的外交败笔，莫过于美俄大国关系重启的接连失败。作为一名民主党总统，奥巴马离任不应该留下破碎的美俄关系这一烂摊子。因为相比讲究单边主义的小布什而言，奥巴马应该更倾向于保持同普京政府的对话，应对地区及全球性挑战。当然，鉴于国内舆论的压力，尤其是国会共和党议员的反对，奥巴马只能从幕后渠道寻找改善对俄关系的方式。&lt;BR&gt;<br/>
&lt;P&gt;　　从目前来看，美俄关系改善主要还是靠“中间力量”或“第三方媒介”，即伊朗核谈判、叙利亚危机、打击IS恐怖势力等。尤其是普京引领的打击IS的国际反恐联盟，应该是奥巴马改善对俄关系的一大契机。&lt;BR&gt;<br/>
&lt;P&gt;　　据CNN12月24日报道，普京计划和宿敌塔利班建立情报共享机制，以打击咋阿富汗境内的IS恐怖势力。俄罗斯外交部称，俄罗斯和塔利班达成的协议仅限于针对IS的情报共享和信息交换。对此，美国国务院方面向俄罗斯媒体称，支持阿富汗的安全与稳定符合俄罗斯等该地区所有行动者的共同利益。美方也希望能找到与俄罗斯合作增强阿富汗安全与稳定性的方式。&lt;BR&gt;<br/>
&lt;P&gt;　　 <br/>
&lt;DIV align=center&gt;&lt;IMG src=&quot;https://10.10.80.111:8080/toproad/jsp/data/image/281537380382538_0.jpg&quot;&gt;&lt;/DIV&gt;<br/>
&lt;TABLE width=&quot;100%&quot;&gt;<br/>
&lt;TBODY&gt;<br/>
&lt;TR&gt;<br/>
&lt;TD align=center&gt;奥巴马离任前不会放弃改善对俄关系？&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;BR&gt;<br/>
&lt;P&gt;　　次日，《华尔街日报》一篇报道引述中东、美国现任和前任官员的话称，奥巴马政府数年来都在与叙利亚政府进行秘密沟通，但是，这些努力都没有阻止叙利亚的动乱，也没有让阿萨德下台。一开始，美国寻求在阿萨德政权上找到些许裂缝以能够进行军事政变，但未取得进展和积极效果。报道称，这种沟通时断时续，都是通过在古巴、俄罗斯、伊朗等“中间人”开展。&lt;BR&gt;<br/>
&lt;P&gt;　　从这两篇报道至少可以看出，奥巴马政府任内并没有放弃同俄罗斯展开对话，尤其是伊朗核协议的谈判，让美俄合作的重要性更加凸显。最重要的是，奥巴马能够摒弃政权更迭的思维，同古巴复交，和塔利班展开对话，就可以看出，他第二任期非常注重在外交领域的历史地位。初选阵营，也有多位参选人不支持通过“政权更迭”的方式来解决叙利亚等国危机。&lt;BR&gt;<br/>
&lt;P&gt;　　具体就打击ISIS和解决叙利亚问题而言，美国方面，除了奥巴马之外，就包括副总统拜登（Joe Biden）和国安顾问赖斯（Susan Rice）。其中，拜登去年10月就已承认，美国对叙反对派的支持促成了ISIS的崛起，叙反对派中的温和派根本无法维持。俄罗斯方面，普京及其亲信一直以来并未放弃同美国改善关系和展开对话的努力。这从叙利亚危机中“化武换和平”就可以看出。当时，奥巴马威胁出兵叙利亚，幸亏有普京调停，奥巴马最终挽回颜面。&lt;BR&gt;<br/>
&lt;P&gt;　　想当年，9•11爆发后，时任俄总统的普京第一时间致电时任美国总统小布什，极力支持美俄合作反恐，并于3个月后访问美国，成为小布什在9•11后接触的第一个外国领导人。虽然这类大国合作背后都有一定的实力及地缘政治博弈，有时也难免尴尬，但在匡扶国际正义方面，两国还是有大国担当的。&lt;BR&gt;<br/>
&lt;P&gt;　　现在，普京“主导”打击ISIS的国际大任，除了同英法等国协同外，更重要还是要和美国合作。如果在这一过程中美俄在叙利亚问题上积累共识，两国关系2016年开始改善就有可能。而且，从目前来看，普京寻求塔利班的支援一定程度上得到美国的认可、甚至支持。 &lt;BR&gt;<br/>
&lt;P&gt;　　其实，“阿萨德下台”这句话奥巴马2011年就已喊出，至今难以收回。虽然现在奥巴马仍在这样说，但明显力度和自信已经不够。而且，克里米亚现状已成定局，美国再怎么坚持过往立场，也于事无补。现在，美俄就阿萨德去留的分歧正在不断缩小。通过反恐领域展开“建设性”合作，弥补其他分歧领域的不足，奥巴马其实也是在离任前找台阶下。&lt;/P&gt;</Content><br/><br/>
<PageLevel>1</PageLevel><br/><br/>
<PageRank>0</PageRank><br/><br/>
<Authors>sy</Authors><br/><br/>
<SrcType>3</SrcType><br/><br/>
<DocFormat>2</DocFormat><br/><br/>